In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

url = 'https://raw.githubusercontent.com/chekirou/International-conflict-prediction/master/data/actual.csv'

In [2]:
df = pd.read_csv(url)

In [4]:
csv1 = pd.read_csv('/Users/yasmeenmahomedy2/code/yasmeeenm/conflict_analysis/old_datasets/csv1.csv')
csv2 = pd.read_csv('/Users/yasmeenmahomedy2/code/yasmeeenm/conflict_analysis/old_datasets/csv2.csv')
csv3 = pd.read_csv('/Users/yasmeenmahomedy2/code/yasmeeenm/conflict_analysis/old_datasets/csv3.csv')
csv4 = pd.read_csv('/Users/yasmeenmahomedy2/code/yasmeeenm/conflict_analysis/old_datasets/csv4.csv')
csv5 = pd.read_csv('/Users/yasmeenmahomedy2/code/yasmeeenm/conflict_analysis/old_datasets/csv5.csv')
csv6 = pd.read_csv('/Users/yasmeenmahomedy2/code/yasmeeenm/conflict_analysis/old_datasets/csv6.csv')
csv_pov = pd.read_csv('/Users/yasmeenmahomedy2/code/yasmeeenm/conflict_analysis/other peoples notebooks/poverty_df.csv')

In [5]:
csv1['CountryYear'] = csv1['Country']+csv1['Year'].astype(str)
csv2['CountryYear'] = csv2['Country']+csv2['Year'].astype(str)
csv3['CountryYear'] = csv3['Country']+csv3['Year'].astype(str)
csv4['CountryYear'] = csv4['Country']+csv4['Year'].astype(str)
csv5['CountryYear'] = csv5['Country']+csv5['Year'].astype(str)
csv6['CountryYear'] = csv6['Country']+csv6['Year'].astype(str)

In [6]:
csv_12 = pd.merge(csv1,csv2,on='CountryYear',how='outer')
csv_123 = pd.merge(csv_12,csv3,on='CountryYear',how='outer')
csv_1234 = pd.merge(csv_123,csv4,on='CountryYear',how='outer')
csv_12345 = pd.merge(csv_1234,csv5,on='CountryYear',how='outer')
csv_full = pd.merge(csv_12345,csv6,on='CountryYear',how='outer')

/var/folders/ty/xzkrlw3n681fsxzmh9cl7wq00000gq/T/ipykernel_3248/2404285424.py:3: FutureWarning: Passing 'suffixes' which cause duplicate columns {'Country_x', 'Code_x', 'Year_x', 'ContinentCode_x'} in the result is deprecated and will raise a MergeError in a future version.
  csv_1234 = pd.merge(csv_123,csv4,on='CountryYear',how='outer')
/var/folders/ty/xzkrlw3n681fsxzmh9cl7wq00000gq/T/ipykernel_3248/2404285424.py:5: FutureWarning: Passing 'suffixes' which cause duplicate columns {'Country_x', 'Code_x', 'Year_x', 'ContinentCode_x'} in the result is deprecated and will raise a MergeError in a future version.
  csv_full = pd.merge(csv_12345,csv6,on='CountryYear',how='outer')

In [39]:
conflicts = pd.read_csv('/Users/yasmeenmahomedy2/Downloads/civil_war_dataset - Combined, from 1970.csv')
conflicts

,Unnamed: 0,Country,Year,Year -1,Year -2,Year -3,Year -4,Year -5
0,NaN,Lebanon,1975,1974,1973,1972,1971,1970
1,NaN,Mozambique,1975,1974,1973,1972,1971,1970
2,NaN,Angola,1975,1974,1973,1972,1971,1970
3,NaN,Indonesia,1976,1975,1974,1973,1972,1971
4,NaN,Afghanistan,1978,1977,1976,1975,1974,1973
...,...,...,...,...,...,...,...,...
106,NaN,Peru,2022,2021,2020,2019,2018,2017
107,NaN,Ecuador,2022,2021,2020,2019,2018,2017
108,NaN,Uzbekistan,2022,2021,2020,2019,2018,2017
109,NaN,Sri Lanka,2022,2021,2020,2019,2018,2017
110,NaN,Kazakhstan,2022,2021,2020,2019,2018,2017

In [40]:
def get_year(row):
    
    year_value = row['CountryYear'][-4:]
    
    return int(year_value)

In [41]:
def get_country(row):
    
    country_name = row['CountryYear'][:-4]

    return country_name

In [42]:
csv_full['year_all'] = csv_full.apply(lambda x: get_year(x),axis=1)

In [43]:
csv_full['country_all'] = csv_full.apply(lambda x: get_country(x), axis=1)

In [34]:
csv_full['conflict_id'] =0
conflicts

csv_full[(csv_full['country_all']=='USA') & (csv_full['year_all']>1994)]

,Country_x,Code_x,ContinentCode_x,Year_x,Military spending percent of total government spending,Arms imports million constant U.S. dollars,Cost of living index world average = 100,Food price index world average = 100,Housing and utilities price index world average = 100,Healthcare price index world average = 100,...,Economic decline index 0 (low) - 10 (high),Uneven economic development index 0 (low) - 10 (high),State legitimacy index 0 (high) - 10 (low),Human rights and rule of law index 0 (high) - 10 (low),Demographic pressures 0 (low) - 10 (high),Refugees and displaced persons index 0 (low) - 10 (high),External interventions index 0 (low) - 10 (high),year_all,country_all,conflict_id
8438,USA,USA,NaN,1995.0,NaN,757.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1995,USA,0
8439,USA,USA,NaN,1996.0,NaN,557.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1996,USA,0
8440,USA,USA,NaN,1997.0,NaN,582.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1997,USA,0
8441,USA,USA,NaN,1998.0,NaN,266.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1998,USA,0
8442,USA,USA,NaN,1999.0,NaN,222.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1999,USA,0
8443,USA,USA,NaN,2000.0,NaN,336.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2000,USA,0
8444,USA,USA,NaN,2001.0,9.56,499.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2001,USA,0
8445,USA,USA,NaN,2002.0,10.28,511.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2002,USA,0
8446,USA,USA,NaN,2003.0,11.30,610.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2003,USA,0
8447,USA,USA,NaN,2004.0,11.97,578.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2004,USA,0
8448,USA,USA,NaN,2005.0,12.05,537.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2005,USA,0
8449,USA,USA,NaN,2006.0,12.00,646.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2006,USA,0
8450,USA,USA,NaN,2007.0,11.79,832.0,NaN,NaN,NaN,NaN,...,1.8,5.8,2.8,4.6,3.5,5.5,1.0,2007,USA,0
8451,USA,USA,NaN,2008.0,11.97,967.0,NaN,NaN,NaN,NaN,...,2.3,5.5,3.0,4.2,3.5,4.0,1.0,2008,USA,0
8452,USA,USA,NaN,2009.0,11.78,977.0,NaN,NaN,NaN,NaN,...,2.9,5.3,3.0,4.0,3.1,3.7,1.5,2009,USA,0
8453,USA,USA,NaN,2010.0,12.33,1091.0,NaN,NaN,NaN,NaN,...,4.0,5.4,2.5,3.7,3.1,3.2,1.5,2010,USA,0
8454,USA,USA,NaN,2011.0,12.44,1012.0,NaN,NaN,NaN,NaN,...,3.7,5.4,2.2,3.3,3.4,2.9,1.3,2011,USA,0
8455,USA,USA,NaN,2012.0,12.02,1207.0,NaN,NaN,NaN,NaN,...,3.4,5.1,2.6,3.5,3.3,2.6,1.0,2012,USA,0
8456,USA,USA,NaN,2013.0,11.25,791.0,NaN,NaN,NaN,NaN,...,3.2,4.8,2.3,3.2,3.0,2.3,1.0,2013,USA,0
8457,USA,USA,NaN,2014.0,10.42,590.0,NaN,NaN,NaN,NaN,...,3.1,4.5,2.4,3.5,3.3,2.4,1.3,2014,USA,0
8458,USA,USA,NaN,2015.0,9.89,513.0,NaN,NaN,NaN,NaN,...,2.8,4.8,2.4,3.7,3.0,2.1,1.1,2015,USA,0
8459,USA,USA,NaN,2016.0,9.62,451.0,NaN,NaN,NaN,NaN,...,2.5,4.5,2.1,3.4,3.0,2.1,0.9,2016,USA,0
8460,USA,USA,NaN,2017.0,9.37,516.0,143.34,123.827,170.234,179.52,...,2.4,4.3,1.9,3.2,2.8,2.0,1.2,2017,USA,0
8461,USA,USA,NaN,2018.0,9.36,380.0,NaN,NaN,NaN,NaN,...,2.3,4.0,2.4,3.3,3.3,2.1,1.5,2018,USA,0
8462,USA,USA,NaN,2019.0,9.59,866.0,NaN,NaN,NaN,NaN,...,2.1,3.7,2.6,3.8,3.3,2.4,1.6,2019,USA,0
8463,USA,USA,NaN,2020.0,7.93,687.0,NaN,NaN,NaN,NaN,...,1.8,3.4,2.9,3.9,3.0,2.1,1.3,2020,USA,0
8464,USA,USA,NaN,2021.0,NaN,NaN,NaN,NaN,NaN,NaN,...,2.1,3.7,3.5,4.4,5.0,2.3,1.0,2021,USA,0
12489,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.8,3.7,4.5,4.5,5.5,2.5,0.7,2022,USA,0

In [ ]:
#1990

In [36]:
def get_year(row):
    
    year_value = row['CountryYear'][-4:]
    
    return int(year_value)

In [45]:
my_list = []

def get_hist_data(country,year,lookback):
    
    early_year = lookback
    hist_data = csv_full[(csv_full['country_all']==country) & (csv_full['year_all'] <= (year -1)) & (csv_full['year_all'] > (year -1 - early_year))]
    while hist_data.shape[0] < lookback:
        early_year += 1
        hist_data = csv_full[(csv_full['country_all']==country) & (csv_full['year_all'] <= (year -1)) & (csv_full['year_all'] > (year -1 - early_year))]
    return hist_data

for index, row in conflicts.iterrows():

    my_list.append(get_hist_data(row['Country'],row['Year'],5))


get_hist_data('USA',2010,10)

,Country_x,Code_x,ContinentCode_x,Year_x,Military spending percent of total government spending,Arms imports million constant U.S. dollars,Cost of living index world average = 100,Food price index world average = 100,Housing and utilities price index world average = 100,Healthcare price index world average = 100,...,Economic decline index 0 (low) - 10 (high),Uneven economic development index 0 (low) - 10 (high),State legitimacy index 0 (high) - 10 (low),Human rights and rule of law index 0 (high) - 10 (low),Demographic pressures 0 (low) - 10 (high),Refugees and displaced persons index 0 (low) - 10 (high),External interventions index 0 (low) - 10 (high),year_all,country_all,conflict_id
8443,USA,USA,NaN,2000.0,NaN,336.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2000,USA,0
8444,USA,USA,NaN,2001.0,9.56,499.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2001,USA,0
8445,USA,USA,NaN,2002.0,10.28,511.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2002,USA,0
8446,USA,USA,NaN,2003.0,11.30,610.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2003,USA,0
8447,USA,USA,NaN,2004.0,11.97,578.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2004,USA,0
8448,USA,USA,NaN,2005.0,12.05,537.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2005,USA,0
8449,USA,USA,NaN,2006.0,12.00,646.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2006,USA,0
8450,USA,USA,NaN,2007.0,11.79,832.0,NaN,NaN,NaN,NaN,...,1.8,5.8,2.8,4.6,3.5,5.5,1.0,2007,USA,0
8451,USA,USA,NaN,2008.0,11.97,967.0,NaN,NaN,NaN,NaN,...,2.3,5.5,3.0,4.2,3.5,4.0,1.0,2008,USA,0
8452,USA,USA,NaN,2009.0,11.78,977.0,NaN,NaN,NaN,NaN,...,2.9,5.3,3.0,4.0,3.1,3.7,1.5,2009,USA,0

In [46]:
for i in range(len(my_list)):
    my_list[i]['conflict_id'] = i

/var/folders/ty/xzkrlw3n681fsxzmh9cl7wq00000gq/T/ipykernel_3248/729059741.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  my_list[i]['conflict_id'] = i

In [47]:
for i in range(len(my_list)):
    if len(my_list[i]) < 5:
        print(i)

In [48]:
final_df = pd.DataFrame(columns=my_list[100].columns)

In [49]:
final_df

Empty DataFrame
Columns: [Country_x, Code_x, ContinentCode_x, Year_x, Military spending percent of total government spending , Arms imports million constant U.S. dollars, Cost of living index world average = 100, Food price index world average = 100, Housing and utilities price index world average  = 100, Healthcare price index world average = 100, Happiness Index 0 (unhappy) - 10 (happy), Human Development Index (0 - 1), CountryYear, Country_y, Code_y, ContinentCode_y, Year_y, Economic growth: the rate of change of real GDP, GDP per capita current U.S. dollars, GDP per capita Purchasing Power Parity, Capital investment as percent of GDP, Inflation: percent change in the Consumer Price Index, Unemployment rate, Youth unemployment ages 15-24, Labor force participation rate, Trade openness: exports plus imports as percent of GDP, Foreign Direct Investment percent of GDP, Trade balance as percent of GDP, External debt percent of Gross National Income, Government spending as percent of GDP, Fiscal balance percent of GDP, Government debt as percent of GDP, Foreign aid and official development assistance received, Country_x, Code_x, ContinentCode_x, Year_x, Rule of law index (-2.5 weak; 2.5 strong), Government effectiveness index (-2.5 weak; 2.5 strong), Control of corruption (-2.5 weak; 2.5 strong), Regulatory quality index (-2.5 weak; 2.5 strong), Voice and accountability index (-2.5 weak; 2.5 strong), Political stability index (-2.5 weak; 2.5 strong), Corruption Perceptions Index 100 = no corruption, Political rights index 7 (weak) - 1 (strong), Civil liberties index 7 (weak) - 1 (strong) , Shadow economy percent of GDP, Internet users percent of population, Mobile network coverage percent of the population, Gasoline prices at the pump in dollars per liter, Diesel prices at the pump in dollars per liter, Income from natural resources percent of GDP, Access to electricity percent of the population, Country_y, Code_y, ContinentCode_y, Year_y, Food production index (2004-2006 = 100), Banking system z-scores, Real interest rate: Bank lending rate minus inflation, Freedom from corruption index (0-100), Labor freedom index (0-100), Economic freedom overall index (0-100), Population size in millions, Rural population percent of total population, Refugee population, Migrant population percent of total population, Population growth percent, Life expectancy in years, Death rate per 1000 people, Suicide mortality rate per 100000 population, Country_x, Code_x, ContinentCode_x, Year_x, Deaths of children under five years of age per 1000 live births, Doctors per 1000 people, Gini income inequality index, Poverty percent of population, Poverty ratio percent living on less than 1.90 USD a day, Poverty ratio percent living on less than 5.50 USD a day, Percent income earned by the top 10 percent of earners, Public spending on education percent of GDP, Literacy rate, Globalization index (0-100), Economic globalization index (0-100), Political globalization index (0-100), Social globalization index (0-100), Number of prisoners per 100000 people, Homicides per 100000 people, Country_y, Code_y, ContinentCode_y, Year_y, People practicing Judaism as percent of the population, Buddhists as percent of the total population, People practicing Hinduism as percent of the population, Shia Muslims as percent of the total population, Sunni Muslims as percent of the total population, Christians as percent of the total population, ...]
Index: []

[0 rows x 117 columns]

In [51]:
for i in range(len(my_list)):
    
    final_df = pd.concat([final_df,my_list[i]])

In [52]:
final_df.shape

(555, 117)

## Drop Features

In [53]:
final_df.shape

(555, 117)

In [54]:
to_drop  = pd.DataFrame(final_df.isna().sum()/555)
len(to_drop)

117

In [55]:
to_drop_list = to_drop[to_drop[0]>0.7].index.values.tolist()
len(to_drop_list)

25

In [56]:
for i in to_drop_list:
    final_df.drop(columns=i, axis=1, inplace=True)

In [57]:
final_df['CountryYear']

4437       Lebanon1971
4438       Lebanon1972
4439       Lebanon1973
4440       Lebanon1974
9937       Lebanon1970
             ...
4163    Kazakhstan2017
4164    Kazakhstan2018
4165    Kazakhstan2019
4166    Kazakhstan2020
4167    Kazakhstan2021
Name: CountryYear, Length: 555, dtype: object

# Dropping data for the imputer

In [58]:
bin_list = ['Country_x','Code_x','Country_y','Year_x','Year_y','Code_y','ContinentCode_y','ContinentCode_x','Sunni Muslims as percent of the total population','Christians as percent of the total population']

In [59]:
cleaner_df = final_df.drop(columns=bin_list)

In [60]:
cleaner_df['conflict_id']=cleaner_df['conflict_id'].astype(int)

# Grouping Data

In [62]:
grouped_df = cleaner_df.groupby(by='conflict_id').mean()

/var/folders/ty/xzkrlw3n681fsxzmh9cl7wq00000gq/T/ipykernel_3248/2490057627.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  grouped_df = cleaner_df.groupby(by='conflict_id').mean()

In [63]:
grouped_df.columns

Index(['Military spending percent of total government spending ',
       'Arms imports million constant U.S. dollars',
       'Human Development Index (0 - 1)',
       'Economic growth: the rate of change of real GDP',
       'GDP per capita current U.S. dollars',
       'GDP per capita Purchasing Power Parity',
       'Capital investment as percent of GDP',
       'Inflation: percent change in the Consumer Price Index',
       'Unemployment rate', 'Youth unemployment ages 15-24',
       'Labor force participation rate',
       'Trade openness: exports plus imports as percent of GDP',
       'Foreign Direct Investment percent of GDP',
       'Trade balance as percent of GDP',
       'External debt percent of Gross National Income',
       'Government spending as percent of GDP',
       'Fiscal balance percent of GDP', 'Government debt as percent of GDP',
       'Foreign aid and official development assistance received',
       'Rule of law index (-2.5 weak; 2.5 strong)',
       'Government effectiveness index (-2.5 weak; 2.5 strong)',
       'Control of corruption (-2.5 weak; 2.5 strong)',
       'Regulatory quality index (-2.5 weak; 2.5 strong)',
       'Voice and accountability index (-2.5 weak; 2.5 strong)',
       'Political stability index (-2.5 weak; 2.5 strong)',
       'Corruption Perceptions Index 100 = no corruption',
       'Political rights index 7 (weak) - 1 (strong)',
       'Civil liberties index 7 (weak) - 1 (strong) ',
       'Shadow economy percent of GDP', 'Internet users percent of population',
       'Income from natural resources percent of GDP',
       'Access to electricity percent of the population',
       'Food production index (2004-2006 = 100)', 'Banking system z-scores',
       'Real interest rate: Bank lending rate minus inflation',
       'Freedom from corruption index (0-100)', 'Labor freedom index (0-100)',
       'Economic freedom overall index (0-100)', 'Population size in millions',
       'Rural population percent of total population', 'Refugee population',
       'Population growth percent', 'Life expectancy in years',
       'Death rate per 1000 people',
       'Suicide mortality rate per 100000 population',
       'Deaths of children under five years of age per 1000 live births',
       'Public spending on education percent of GDP',
       'Globalization index (0-100)', 'Economic globalization index (0-100)',
       'Political globalization index (0-100)',
       'Social globalization index (0-100)', 'Homicides per 100000 people',
       'Security threats index 0 (low) - 10 (high)',
       'Factionalized elites index 0 (low) - 10 (high)',
       'Group grievance index 0 (low) - 10 (high)',
       'Economic decline index 0 (low) - 10 (high)',
       'Uneven economic development index 0 (low) - 10 (high)',
       'State legitimacy index 0 (high) - 10 (low)',
       'Human rights and rule of law index 0 (high) - 10 (low)',
       'Demographic pressures 0 (low) - 10 (high)',
       'Refugees and displaced persons index 0 (low) - 10 (high)',
       'External interventions index 0 (low) - 10 (high)'],
      dtype='object')

# Control dataset

In [64]:
conflict_years = final_df['CountryYear']

In [65]:
csv4_after_1980 = csv_full[csv_full['year_all'] > 1975]
csv4_after_1980_noconflict = csv4_after_1980[csv4_after_1980.CountryYear.isin(conflict_years)==False]
csv4_after_1980.shape[0] - csv4_after_1980_noconflict.shape[0]

496

In [66]:
def slice_fn(sample):
    year = int(sample[-4:])
    words = [sample[:-4]+str(year-i-1) for i in range(4)]
    words.append(sample)
    return words

In [67]:
from itertools import chain

sample_list = []

control_sample = csv4_after_1980.sample(110)

for index,row in control_sample.iterrows():
    sample_list.append(get_hist_data(row['country_all'],row['year_all'],5))

sample_full = sample_list[0]

for i in range(1,len(sample_list)):
    
    sample_full = pd.concat([sample_full,sample_list[i]])

In [68]:
id_list = list(range(111,221))*5

In [69]:
id_list = sorted(id_list)

In [70]:
sample_full['conflict_id'] = id_list
sample_full

,Country_x,Code_x,ContinentCode_x,Year_x,Military spending percent of total government spending,Arms imports million constant U.S. dollars,Cost of living index world average = 100,Food price index world average = 100,Housing and utilities price index world average = 100,Healthcare price index world average = 100,...,Economic decline index 0 (low) - 10 (high),Uneven economic development index 0 (low) - 10 (high),State legitimacy index 0 (high) - 10 (low),Human rights and rule of law index 0 (high) - 10 (low),Demographic pressures 0 (low) - 10 (high),Refugees and displaced persons index 0 (low) - 10 (high),External interventions index 0 (low) - 10 (high),year_all,country_all,conflict_id
5215,Mongolia,MNG,AS,1993.0,4.76,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1993,Mongolia,111
5216,Mongolia,MNG,AS,1994.0,5.50,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1994,Mongolia,111
5217,Mongolia,MNG,AS,1995.0,5.51,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1995,Mongolia,111
5218,Mongolia,MNG,AS,1996.0,5.61,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1996,Mongolia,111
5219,Mongolia,MNG,AS,1997.0,5.13,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1997,Mongolia,111
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8840,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1987,Antigua and Barbuda,220
8841,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1988,Antigua and Barbuda,220
8842,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1989,Antigua and Barbuda,220
8843,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1990,Antigua and Barbuda,220
8844,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1991,Antigua and Barbuda,220

In [71]:
control_groupedby = sample_full.groupby('conflict_id').mean()

/var/folders/ty/xzkrlw3n681fsxzmh9cl7wq00000gq/T/ipykernel_3248/3478027142.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  control_groupedby = sample_full.groupby('conflict_id').mean()

In [101]:
columns_to_keep = list(grouped_df.columns)

In [102]:
sample_full_clean = control_groupedby.drop(columns=[col for col in control_groupedby if col not in columns_to_keep])

sample_full_clean.isna().sum()

sample_full_clean

,Military spending percent of total government spending,Arms imports million constant U.S. dollars,Human Development Index (0 - 1),Economic growth: the rate of change of real GDP,GDP per capita current U.S. dollars,GDP per capita Purchasing Power Parity,Capital investment as percent of GDP,Inflation: percent change in the Consumer Price Index,Unemployment rate,Youth unemployment ages 15-24,...,Security threats index 0 (low) - 10 (high),Factionalized elites index 0 (low) - 10 (high),Group grievance index 0 (low) - 10 (high),Economic decline index 0 (low) - 10 (high),Uneven economic development index 0 (low) - 10 (high),State legitimacy index 0 (high) - 10 (low),Human rights and rule of law index 0 (high) - 10 (low),Demographic pressures 0 (low) - 10 (high),Refugees and displaced persons index 0 (low) - 10 (high),External interventions index 0 (low) - 10 (high)
conflict_id,,,,,,,,,,,,,,,,,,,,,
111,5.3020,NaN,0.5550,2.296,492.784,4075.330,23.630,87.86,6.148,10.690,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
112,NaN,NaN,NaN,NaN,51042.914,NaN,19.866,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
113,3.0360,NaN,0.5814,5.918,1339.440,4564.040,28.916,7.42,4.596,8.162,...,5.90,6.30,5.30,7.60,8.70,7.40,5.80,7.80,2.00,5.40
114,NaN,84.8,NaN,1.590,10155.672,NaN,22.294,9.66,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
115,NaN,10.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
216,11.2960,79.8,0.4288,9.370,1108.152,5382.944,29.976,85.24,3.944,8.664,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
217,9.8375,11.0,0.8278,8.302,37366.076,88824.094,32.492,3.92,0.858,2.520,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
218,8.4640,67.0,0.5664,7.080,1184.936,3550.798,22.030,2.78,0.476,0.808,...,6.46,8.28,7.14,6.10,7.04,8.38,7.92,7.18,5.94,7.62
219,NaN,NaN,0.5876,6.590,2497.070,8951.426,60.418,8.40,2.820,8.464,...,5.76,7.54,7.60,6.66,7.84,6.26,7.42,6.60,6.98,7.10
220,NaN,NaN,NaN,4.456,6788.996,15523.475,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Merge and Impute

In [74]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

imputer = IterativeImputer(max_iter=10, random_state=0, missing_values=np.nan)
imputer2 = IterativeImputer(max_iter=10, random_state=0, missing_values=np.nan)

grouped_df['target'] = 1
sample_full_clean['target'] = 0

numerics = ['int16', 'int32', 'int64', 'float16', 'float32', 'float64']


full_dataset = pd.concat([grouped_df,sample_full_clean])

In [75]:
data_numeric = full_dataset.select_dtypes(include=numerics)

imputer.fit(data_numeric)
imputed_final_df = pd.DataFrame(imputer.transform(data_numeric),columns=full_dataset.columns)
imputed_final_df.head()

,Military spending percent of total government spending,Arms imports million constant U.S. dollars,Human Development Index (0 - 1),Economic growth: the rate of change of real GDP,GDP per capita current U.S. dollars,GDP per capita Purchasing Power Parity,Capital investment as percent of GDP,Inflation: percent change in the Consumer Price Index,Unemployment rate,Youth unemployment ages 15-24,...,Factionalized elites index 0 (low) - 10 (high),Group grievance index 0 (low) - 10 (high),Economic decline index 0 (low) - 10 (high),Uneven economic development index 0 (low) - 10 (high),State legitimacy index 0 (high) - 10 (low),Human rights and rule of law index 0 (high) - 10 (low),Demographic pressures 0 (low) - 10 (high),Refugees and displaced persons index 0 (low) - 10 (high),External interventions index 0 (low) - 10 (high),target
0,10.332834,31.250000,0.637333,3.277793,6568.741898,14737.622245,24.525670,31.852616,8.420456,16.757341,...,6.678137,6.406686,6.590181,6.877714,6.892106,5.740121,6.660707,5.188231,6.866158,1.0
1,10.227264,17.024836,0.201477,3.057199,6548.235829,14630.436273,23.937389,245.326283,6.295170,10.939181,...,7.236701,6.393276,8.417060,7.629145,7.238913,6.411564,9.801307,6.769190,8.227023,1.0
2,10.215854,1.000000,0.263478,2.963839,6499.121165,14566.794616,23.944707,258.713018,6.446602,11.198606,...,7.143093,6.582013,7.944436,7.586539,7.138543,5.992649,9.227395,6.347488,7.964936,1.0
3,10.421135,49.400000,0.363115,7.000000,147.340000,5486.179489,17.918000,20.280000,6.609487,10.479216,...,9.200057,9.345425,8.631578,8.918094,8.997021,8.491566,9.693092,7.784232,8.694732,1.0
4,11.020005,131.666667,0.165645,3.565133,184.996000,5815.695732,10.382000,305.888988,7.437646,10.497724,...,8.708224,7.265461,8.951924,8.389520,8.473298,7.236306,10.531740,7.990772,9.412810,1.0

In [76]:
data_numeric2 = grouped_df.select_dtypes(include=numerics)

imputed_conflict_df = pd.DataFrame(imputer2.fit_transform(data_numeric2),columns=data_numeric2.columns)
imputed_control_df = pd.DataFrame(imputer2.fit_transform(sample_full_clean),columns=data_numeric2.columns)

In [77]:
separate_impute_full_df = pd.concat([imputed_control_df,imputed_conflict_df])
separate_impute_full_df['target'] = separate_impute_full_df['target'].astype(int)
separate_impute_full_df
imputed_final_df

,Military spending percent of total government spending,Arms imports million constant U.S. dollars,Human Development Index (0 - 1),Economic growth: the rate of change of real GDP,GDP per capita current U.S. dollars,GDP per capita Purchasing Power Parity,Capital investment as percent of GDP,Inflation: percent change in the Consumer Price Index,Unemployment rate,Youth unemployment ages 15-24,...,Factionalized elites index 0 (low) - 10 (high),Group grievance index 0 (low) - 10 (high),Economic decline index 0 (low) - 10 (high),Uneven economic development index 0 (low) - 10 (high),State legitimacy index 0 (high) - 10 (low),Human rights and rule of law index 0 (high) - 10 (low),Demographic pressures 0 (low) - 10 (high),Refugees and displaced persons index 0 (low) - 10 (high),External interventions index 0 (low) - 10 (high),target
0,10.332834,31.250000,0.637333,3.277793,6568.741898,14737.622245,24.525670,31.852616,8.420456,16.757341,...,6.678137,6.406686,6.590181,6.877714,6.892106,5.740121,6.660707,5.188231,6.866158,1.0
1,10.227264,17.024836,0.201477,3.057199,6548.235829,14630.436273,23.937389,245.326283,6.295170,10.939181,...,7.236701,6.393276,8.417060,7.629145,7.238913,6.411564,9.801307,6.769190,8.227023,1.0
2,10.215854,1.000000,0.263478,2.963839,6499.121165,14566.794616,23.944707,258.713018,6.446602,11.198606,...,7.143093,6.582013,7.944436,7.586539,7.138543,5.992649,9.227395,6.347488,7.964936,1.0
3,10.421135,49.400000,0.363115,7.000000,147.340000,5486.179489,17.918000,20.280000,6.609487,10.479216,...,9.200057,9.345425,8.631578,8.918094,8.997021,8.491566,9.693092,7.784232,8.694732,1.0
4,11.020005,131.666667,0.165645,3.565133,184.996000,5815.695732,10.382000,305.888988,7.437646,10.497724,...,8.708224,7.265461,8.951924,8.389520,8.473298,7.236306,10.531740,7.990772,9.412810,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
216,11.296000,79.800000,0.428800,9.370000,1108.152000,5382.944000,29.976000,85.240000,3.944000,8.664000,...,8.792915,8.347119,8.383915,8.434382,9.461969,8.423105,9.491848,7.293753,9.193930,0.0
217,9.837500,11.000000,0.827800,8.302000,37366.076000,88824.094000,32.492000,3.920000,0.858000,2.520000,...,4.849935,4.692630,2.266981,6.579211,6.784589,7.331849,4.325934,1.859807,2.110726,0.0
218,8.464000,67.000000,0.566400,7.080000,1184.936000,3550.798000,22.030000,2.780000,0.476000,0.808000,...,8.280000,7.140000,6.100000,7.040000,8.380000,7.920000,7.180000,5.940000,7.620000,0.0
219,10.370262,-280.939962,0.587600,6.590000,2497.070000,8951.426000,60.418000,8.400000,2.820000,8.464000,...,7.540000,7.600000,6.660000,7.840000,6.260000,7.420000,6.600000,6.980000,7.100000,0.0
220,10.316743,102.119758,0.688901,4.456000,6788.996000,15523.475000,24.556746,57.321356,6.665825,15.456018,...,6.329178,4.879566,5.974520,6.748113,6.824306,6.157246,6.368891,5.160677,6.311074,0.0

In [81]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

In [82]:
scaler2 = MinMaxScaler()
separate_scaled = pd.DataFrame(scaler2.fit_transform(separate_impute_full_df), columns=separate_impute_full_df.columns)

X2 = separate_scaled.drop(columns=['target'])
y2 = separate_scaled['target']
X_train2, X_test2, y_train2, y_test2 = train_test_split(X2, y2,test_size = 0.3, random_state=5)

In [89]:
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV

In [90]:
bst2 = XGBClassifier(n_estimators=2, max_depth=2, learning_rate=1, objective='binary:logistic')
bst2.fit(X_train2, y_train2)

XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, feature_types=None, gamma=0, gpu_id=-1,
              grow_policy='depthwise', importance_type=None,
              interaction_constraints='', learning_rate=1, max_bin=256,
              max_cat_threshold=64, max_cat_to_onehot=4, max_delta_step=0,
              max_depth=2, max_leaves=0, min_child_weight=1, missing=nan,
              monotone_constraints='()', n_estimators=2, n_jobs=0,
              num_parallel_tree=1, predictor='auto', random_state=0, ...)

In [91]:
preds2 = bst2.predict(X_test2)

accuracy_score(preds2,y_test2)

0.7164179104477612

# Scale whole dataset

In [92]:
from sklearn.preprocessing import MinMaxScaler

In [93]:
scaler = MinMaxScaler()
full_dataset_scaled = pd.DataFrame(scaler.fit_transform(imputed_final_df), columns=imputed_final_df.columns)

# Model

In [94]:
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV


X = full_dataset_scaled.drop(columns=['target'])
y = full_dataset_scaled['target']
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size = 0.3, random_state=5)

In [95]:
y_train.value_counts()

0.0    80
1.0    74
Name: target, dtype: int64

In [96]:
bst = XGBClassifier(n_estimators=2,max_depth=2,learning_rate=1, objective='binary:logistic')

In [97]:
bst.fit(X_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, feature_types=None, gamma=0, gpu_id=-1,
              grow_policy='depthwise', importance_type=None,
              interaction_constraints='', learning_rate=1, max_bin=256,
              max_cat_threshold=64, max_cat_to_onehot=4, max_delta_step=0,
              max_depth=2, max_leaves=0, min_child_weight=1, missing=nan,
              monotone_constraints='()', n_estimators=2, n_jobs=0,
              num_parallel_tree=1, predictor='auto', random_state=0, ...)

In [98]:
preds = bst.predict(X_test)

accuracy_score(preds,y_test)
bst.predict(X_test)

array([0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1,
       0])

In [99]:
import pandas as pd

features = bst.get_booster().feature_names
importances = bst.feature_importances_
feature_importances_df = pd.DataFrame(zip(features, importances), columns=['feature', 'importance']).set_index('feature')
feature_importances_df.sort_values('importance', ascending=False).head(10)

                                                    importance
feature
Rule of law index (-2.5 weak; 2.5 strong)             0.366000
Population size in millions                           0.240171
Voice and accountability index (-2.5 weak; 2.5 ...    0.152637
Uneven economic development index 0 (low) - 10 ...    0.124097
Labor force participation rate                        0.072292
Labor freedom index (0-100)                           0.044803
Military spending percent of total government s...    0.000000
Suicide mortality rate per 100000 population          0.000000
Death rate per 1000 people                            0.000000
Life expectancy in years                              0.000000

In [100]:
def get_imputed_df(country,year,lookback=5):
    df = get_hist_data(country,year,lookback).groupby('country_all',).mean()
    df.drop(columns=[col for col in df if col not in columns_to_keep],inplace=True)
    df['target'] = 0.5
    imputed_df = pd.DataFrame(imputer.transform(df),columns=df.columns)
    imputed_df.drop(columns='target',inplace=True)
    
    
    return imputed_df




def get_prob(country,year,lookback=5):
    
    prob = bst.predict_proba(get_imputed_df(country,year,lookback))[0][1]
    return prob

def prob_series(country,start_year,end_year,lookback=5):
    my_list =[]
    for year in range(start_year,end_year+1):
        my_list.append(get_prob(country,year,lookback))
    return my_list

# NEXT STEPS:
#     - FINE TUNE MODEL PARAMS WITH GRID SEARCH / FEATURE SET TO IMPROVE PERFORMANCE 
#     - DELETE FEATURES SO LESS IMPUTATION/SOME ACTUAL TIME PROGRESS
#     - MORE STREAMLIT/START PUTTING PRESENTATION TOGETHER
#     - TRY GET GRAPH WORKING
    
prob_series('USA',1990,2020)
get_imputed_df('Iran',2019)
prob_series('Norway',1990,2020)

/var/folders/ty/xzkrlw3n681fsxzmh9cl7wq00000gq/T/ipykernel_3248/3709016605.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = get_hist_data(country,year,lookback).groupby('country_all',).mean()
/var/folders/ty/xzkrlw3n681fsxzmh9cl7wq00000gq/T/ipykernel_3248/3709016605.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = get_hist_data(country,year,lookback).groupby('country_all',).mean()
/var/folders/ty/xzkrlw3n681fsxzmh9cl7wq00000gq/T/ipykernel_3248/3709016605.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = get_hist_data(country,year,lookback).groupby('country_all',).mean()
/var/folders/ty/xzkrlw3n681fsxzmh9cl7wq00000gq/T/ipykernel_3248/3709016605.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = get_hist_data(country,year,lookback).groupby('country_all',).mean()
/var/folders/ty/xzkrlw3n681fsxzmh9cl7wq00000gq/T/ipykernel_3248/3709016605.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = get_hist_data(country,year,lookback).groupby('country_all',).mean()
/var/folders/ty/xzkrlw3n681fsxzmh9cl7wq00000gq/T/ipykernel_3248/3709016605.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = get_hist_data(country,year,lookback).groupby('country_all',).mean()
/var/folders/ty/xzkrlw3n681fsxzmh9cl7wq00000gq/T/ipykernel_3248/3709016605.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = get_hist_data(country,year,lookback).groupby('country_all',).mean()
/var/folders/ty/xzkrlw3n681fsxzmh9cl7wq00000gq/T/ipykernel_3248/3709016605.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = get_hist_data(country,year,lookback).groupby('country_all',).mean()
/var/folders/ty/xzkrlw3n681fsxzmh9cl7wq00000gq/T/ipykernel_3248/3709016605.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = get_hist_data(country,year,lookback).groupby('country_all',).mean()
/var/folders/ty/xzkrlw3n681fsxzmh9cl7wq00000gq/T/ipykernel_3248/3709016605.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = get_hist_data(country,year,lookback).groupby('country_all',).mean()
/var/folders/ty/xzkrlw3n681fsxzmh9cl7wq00000gq/T/ipykernel_3248/3709016605.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = get_hist_data(country,year,lookback).groupby('country_all',).mean()
/var/folders/ty/xzkrlw3n681fsxzmh9cl7wq00000gq/T/ipykernel_3248/3709016605.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = get_hist_data(country,year,lookback).groupby('country_all',).mean()
/var/folders/ty/xzkrlw3n681fsxzmh9cl7wq00000gq/T/ipykernel_3248/3709016605.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = get_hist_data(country,year,lookback).groupby('country_all',).mean()
/var/folders/ty/xzkrlw3n681fsxzmh9cl7wq00000gq/T/ipykernel_3248/3709016605.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = get_hist_data(country,year,lookback).groupby('country_all',).mean()
/var/folders/ty/xzkrlw3n681fsxzmh9cl7wq00000gq/T/ipykernel_3248/3709016605.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = get_hist_data(country,year,lookback).groupby('country_all',).mean()
/var/folders/ty/xzkrlw3n681fsxzmh9cl7wq00000gq/T/ipykernel_3248/3709016605.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = get_hist_data(country,year,lookback).groupby('country_all',).mean()
/var/folders/ty/xzkrlw3n681fsxzmh9cl7wq00000gq/T/ipykernel_3248/3709016605.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = get_hist_data(country,year,lookback).groupby('country_all',).mean()
/var/folders/ty/xzkrlw3n681fsxzmh9cl7wq00000gq/T/ipykernel_3248/3709016605.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = get_hist_data(country,year,lookback).groupby('country_all',).mean()
/var/folders/ty/xzkrlw3n681fsxzmh9cl7wq00000gq/T/ipykernel_3248/3709016605.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = get_hist_data(country,year,lookback).groupby('country_all',).mean()
/var/folders/ty/xzkrlw3n681fsxzmh9cl7wq00000gq/T/ipykernel_3248/3709016605.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = get_hist_data(country,year,lookback).groupby('country_all',).mean()
/var/folders/ty/xzkrlw3n681fsxzmh9cl7wq00000gq/T/ipykernel_3248/3709016605.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = get_hist_data(country,year,lookback).groupby('country_all',).mean()
/var/folders/ty/xzkrlw3n681fsxzmh9cl7wq00000gq/T/ipykernel_3248/3709016605.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = get_hist_data(country,year,lookback).groupby('country_all',).mean()
/var/folders/ty/xzkrlw3n681fsxzmh9cl7wq00000gq/T/ipykernel_3248/3709016605.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = get_hist_data(country,year,lookback).groupby('country_all',).mean()
/var/folders/ty/xzkrlw3n681fsxzmh9cl7wq00000gq/T/ipykernel_3248/3709016605.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = get_hist_data(country,year,lookback).groupby('country_all',).mean()
/var/folders/ty/xzkrlw3n681fsxzmh9cl7wq00000gq/T/ipykernel_3248/3709016605.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = get_hist_data(country,year,lookback).groupby('country_all',).mean()
/var/folders/ty/xzkrlw3n681fsxzmh9cl7wq00000gq/T/ipykernel_3248/3709016605.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = get_hist_data(country,year,lookback).groupby('country_all',).mean()
/var/folders/ty/xzkrlw3n681fsxzmh9cl7wq00000gq/T/ipykernel_3248/3709016605.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = get_hist_data(country,year,lookback).groupby('country_all',).mean()
/var/folders/ty/xzkrlw3n681fsxzmh9cl7wq00000gq/T/ipykernel_3248/3709016605.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = get_hist_data(country,year,lookback).groupby('country_all',).mean()
/var/folders/ty/xzkrlw3n681fsxzmh9cl7wq00000gq/T/ipykernel_3248/3709016605.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = get_hist_data(country,year,lookback).groupby('country_all',).mean()
/var/folders/ty/xzkrlw3n681fsxzmh9cl7wq00000gq/T/ipykernel_3248/3709016605.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = get_hist_data(country,year,lookback).groupby('country_all',).mean()

/var/folders/ty/xzkrlw3n681fsxzmh9cl7wq00000gq/T/ipykernel_3248/3709016605.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = get_hist_data(country,year,lookback).groupby('country_all',).mean()
/var/folders/ty/xzkrlw3n681fsxzmh9cl7wq00000gq/T/ipykernel_3248/3709016605.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = get_hist_data(country,year,lookback).groupby('country_all',).mean()
/var/folders/ty/xzkrlw3n681fsxzmh9cl7wq00000gq/T/ipykernel_3248/3709016605.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = get_hist_data(country,year,lookback).groupby('country_all',).mean()
/var/folders/ty/xzkrlw3n681fsxzmh9cl7wq00000gq/T/ipykernel_3248/3709016605.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = get_hist_data(country,year,lookback).groupby('country_all',).mean()
/var/folders/ty/xzkrlw3n681fsxzmh9cl7wq00000gq/T/ipykernel_3248/3709016605.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = get_hist_data(country,year,lookback).groupby('country_all',).mean()
/var/folders/ty/xzkrlw3n681fsxzmh9cl7wq00000gq/T/ipykernel_3248/3709016605.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = get_hist_data(country,year,lookback).groupby('country_all',).mean()
/var/folders/ty/xzkrlw3n681fsxzmh9cl7wq00000gq/T/ipykernel_3248/3709016605.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = get_hist_data(country,year,lookback).groupby('country_all',).mean()
/var/folders/ty/xzkrlw3n681fsxzmh9cl7wq00000gq/T/ipykernel_3248/3709016605.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = get_hist_data(country,year,lookback).groupby('country_all',).mean()
/var/folders/ty/xzkrlw3n681fsxzmh9cl7wq00000gq/T/ipykernel_3248/3709016605.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = get_hist_data(country,year,lookback).groupby('country_all',).mean()
/var/folders/ty/xzkrlw3n681fsxzmh9cl7wq00000gq/T/ipykernel_3248/3709016605.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = get_hist_data(country,year,lookback).groupby('country_all',).mean()
/var/folders/ty/xzkrlw3n681fsxzmh9cl7wq00000gq/T/ipykernel_3248/3709016605.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = get_hist_data(country,year,lookback).groupby('country_all',).mean()
/var/folders/ty/xzkrlw3n681fsxzmh9cl7wq00000gq/T/ipykernel_3248/3709016605.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = get_hist_data(country,year,lookback).groupby('country_all',).mean()
/var/folders/ty/xzkrlw3n681fsxzmh9cl7wq00000gq/T/ipykernel_3248/3709016605.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = get_hist_data(country,year,lookback).groupby('country_all',).mean()
/var/folders/ty/xzkrlw3n681fsxzmh9cl7wq00000gq/T/ipykernel_3248/3709016605.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = get_hist_data(country,year,lookback).groupby('country_all',).mean()
/var/folders/ty/xzkrlw3n681fsxzmh9cl7wq00000gq/T/ipykernel_3248/3709016605.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = get_hist_data(country,year,lookback).groupby('country_all',).mean()
/var/folders/ty/xzkrlw3n681fsxzmh9cl7wq00000gq/T/ipykernel_3248/3709016605.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = get_hist_data(country,year,lookback).groupby('country_all',).mean()
/var/folders/ty/xzkrlw3n681fsxzmh9cl7wq00000gq/T/ipykernel_3248/3709016605.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = get_hist_data(country,year,lookback).groupby('country_all',).mean()
/var/folders/ty/xzkrlw3n681fsxzmh9cl7wq00000gq/T/ipykernel_3248/3709016605.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = get_hist_data(country,year,lookback).groupby('country_all',).mean()
/var/folders/ty/xzkrlw3n681fsxzmh9cl7wq00000gq/T/ipykernel_3248/3709016605.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = get_hist_data(country,year,lookback).groupby('country_all',).mean()
/var/folders/ty/xzkrlw3n681fsxzmh9cl7wq00000gq/T/ipykernel_3248/3709016605.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = get_hist_data(country,year,lookback).groupby('country_all',).mean()
/var/folders/ty/xzkrlw3n681fsxzmh9cl7wq00000gq/T/ipykernel_3248/3709016605.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = get_hist_data(country,year,lookback).groupby('country_all',).mean()
/var/folders/ty/xzkrlw3n681fsxzmh9cl7wq00000gq/T/ipykernel_3248/3709016605.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = get_hist_data(country,year,lookback).groupby('country_all',).mean()
/var/folders/ty/xzkrlw3n681fsxzmh9cl7wq00000gq/T/ipykernel_3248/3709016605.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = get_hist_data(country,year,lookback).groupby('country_all',).mean()
/var/folders/ty/xzkrlw3n681fsxzmh9cl7wq00000gq/T/ipykernel_3248/3709016605.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = get_hist_data(country,year,lookback).groupby('country_all',).mean()
/var/folders/ty/xzkrlw3n681fsxzmh9cl7wq00000gq/T/ipykernel_3248/3709016605.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = get_hist_data(country,year,lookback).groupby('country_all',).mean()
/var/folders/ty/xzkrlw3n681fsxzmh9cl7wq00000gq/T/ipykernel_3248/3709016605.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = get_hist_data(country,year,lookback).groupby('country_all',).mean()
/var/folders/ty/xzkrlw3n681fsxzmh9cl7wq00000gq/T/ipykernel_3248/3709016605.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = get_hist_data(country,year,lookback).groupby('country_all',).mean()
/var/folders/ty/xzkrlw3n681fsxzmh9cl7wq00000gq/T/ipykernel_3248/3709016605.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = get_hist_data(country,year,lookback).groupby('country_all',).mean()
/var/folders/ty/xzkrlw3n681fsxzmh9cl7wq00000gq/T/ipykernel_3248/3709016605.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = get_hist_data(country,year,lookback).groupby('country_all',).mean()
/var/folders/ty/xzkrlw3n681fsxzmh9cl7wq00000gq/T/ipykernel_3248/3709016605.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = get_hist_data(country,year,lookback).groupby('country_all',).mean()
/var/folders/ty/xzkrlw3n681fsxzmh9cl7wq00000gq/T/ipykernel_3248/3709016605.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = get_hist_data(country,year,lookback).groupby('country_all',).mean()

/var/folders/ty/xzkrlw3n681fsxzmh9cl7wq00000gq/T/ipykernel_3248/3709016605.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = get_hist_data(country,year,lookback).groupby('country_all',).mean()
/var/folders/ty/xzkrlw3n681fsxzmh9cl7wq00000gq/T/ipykernel_3248/3709016605.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = get_hist_data(country,year,lookback).groupby('country_all',).mean()

[0.20651874,
 0.20651874,
 0.20651874,
 0.20651874,
 0.20651874,
 0.20651874,
 0.20651874,
 0.20651874,
 0.20651874,
 0.20651874,
 0.20651874,
 0.20651874,
 0.20651874,
 0.20651874,
 0.20651874,
 0.20651874,
 0.20651874,
 0.20651874,
 0.20651874,
 0.20651874,
 0.20651874,
 0.20651874,
 0.20651874,
 0.20651874,
 0.20651874,
 0.20651874,
 0.20651874,
 0.20651874,
 0.20651874,
 0.20651874,
 0.20651874]

# Grid Search

In [103]:
from sklearn.model_selection import GridSearchCV

from sklearn.model_selection import RandomizedSearchCV

from sklearn.svm import SVC

In [104]:
estimator = XGBClassifier(
    objective= 'binary:logistic',
    nthread=4,
    seed=42)

In [105]:
parameters = {
    'max_depth': range (2, 10, 1),
    'n_estimators': range(60, 220, 40),
    'learning_rate': [0.1, 0.01, 0.05]
}

In [106]:
grid_search = GridSearchCV(
    estimator=estimator,
    param_grid=parameters,
    scoring = 'roc_auc',
    n_jobs = 10,
    cv = 10,
    verbose=True
)

In [108]:
grid_search.fit(X_train, y_train)

Fitting 10 folds for each of 96 candidates, totalling 960 fits

GridSearchCV(cv=10,
             estimator=XGBClassifier(base_score=None, booster=None,
                                     callbacks=None, colsample_bylevel=None,
                                     colsample_bynode=None,
                                     colsample_bytree=None,
                                     early_stopping_rounds=None,
                                     enable_categorical=False, eval_metric=None,
                                     feature_types=None, gamma=None,
                                     gpu_id=None, grow_policy=None,
                                     importance_type=None,
                                     interaction_constraints=None,
                                     learning_rate=None...
                                     max_cat_to_onehot=None,
                                     max_delta_step=None, max_depth=None,
                                     max_leaves=None, min_child_weight=None,
                                     missing=nan, monotone_constraints=None,
                                     n_estimators=100, n_jobs=None, nthread=4,
                                     num_parallel_tree=None, predictor=None, ...),
             n_jobs=10,
             param_grid={'learning_rate': [0.1, 0.01, 0.05],
                         'max_depth': range(2, 10),
                         'n_estimators': range(60, 220, 40)},
             scoring='roc_auc', verbose=True)

In [109]:
grid_search.best_estimator_

XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, feature_types=None, gamma=0, gpu_id=-1,
              grow_policy='depthwise', importance_type=None,
              interaction_constraints='', learning_rate=0.01, max_bin=256,
              max_cat_threshold=64, max_cat_to_onehot=4, max_delta_step=0,
              max_depth=3, max_leaves=0, min_child_weight=1, missing=nan,
              monotone_constraints='()', n_estimators=180, n_jobs=4, nthread=4,
              num_parallel_tree=1, predictor='auto', ...)

# AutoML

In [111]:
from flaml import AutoML
from flaml.data import load_openml_dataset

ModuleNotFoundError: No module named 'flaml'