# Data

In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

url = 'https://raw.githubusercontent.com/chekirou/International-conflict-prediction/master/data/actual.csv'

In [ ]:
df = pd.read_csv(url)

In [ ]:
csv1 = pd.read_csv('csv1.csv')
csv2 = pd.read_csv('csv2.csv')
csv3 = pd.read_csv('csv3.csv')
csv4 = pd.read_csv('csv4.csv')
csv5 = pd.read_csv('csv5.csv')
csv6 = pd.read_csv('csv6.csv')

In [ ]:
csv1['CountryYear'] = csv1['Country']+csv1['Year'].astype(str)
csv2['CountryYear'] = csv2['Country']+csv2['Year'].astype(str)
csv3['CountryYear'] = csv3['Country']+csv3['Year'].astype(str)
csv4['CountryYear'] = csv4['Country']+csv4['Year'].astype(str)
csv5['CountryYear'] = csv5['Country']+csv5['Year'].astype(str)
csv6['CountryYear'] = csv6['Country']+csv6['Year'].astype(str)

In [ ]:
csv_12 = pd.merge(csv1,csv2,on='CountryYear',how='outer')
csv_123 = pd.merge(csv_12,csv3,on='CountryYear',how='outer')
csv_1234 = pd.merge(csv_123,csv4,on='CountryYear',how='outer')
csv_12345 = pd.merge(csv_1234,csv5,on='CountryYear',how='outer')
csv_full = pd.merge(csv_12345,csv6,on='CountryYear',how='outer')

In [6]:
conflicts = pd.read_csv('conflict_data_1970.csv')

In [45]:
conflicts
csv_full['conflict_id'] =0

In [102]:
csv3[csv3['Year'] > 1980].isna().sum() / len(csv3[csv3['Year'] > 1980])

Country                                                   0.000000
Code                                                      0.000000
ContinentCode                                             0.129179
Year                                                      0.000000
Rule of law index (-2.5 weak; 2.5 strong)                 0.437690
Government effectiveness index (-2.5 weak; 2.5 strong)    0.448708
Control of corruption (-2.5 weak; 2.5 strong)             0.446429
Regulatory quality index (-2.5 weak; 2.5 strong)          0.448328
Voice and accountability index (-2.5 weak; 2.5 strong)    0.436677
Political stability index (-2.5 weak; 2.5 strong)         0.439970
Corruption Perceptions Index 100 = no corruption          0.582067
Political rights index 7 (weak) - 1 (strong)              0.091185
Civil liberties index 7 (weak) - 1 (strong)               0.089919
Shadow economy percent of GDP                             0.499747
Internet users percent of population                      0.256586
Mobile network coverage percent of the population         0.912107
Gasoline prices at the pump in dollars per liter          0.770010
Diesel prices at the pump in dollars per liter            0.772290
Income from natural resources percent of GDP              0.087386
Access to electricity percent of the population           0.320542
dtype: float64

In [114]:
csv4[csv4['Country']=='Iran']

,Country,Code,ContinentCode,Year,Food production index (2004-2006 = 100),Banking system z-scores,Real interest rate: Bank lending rate minus inflation,Freedom from corruption index (0-100),Labor freedom index (0-100),Economic freedom overall index (0-100),Population size in millions,Rural population percent of total population,Refugee population,Migrant population percent of total population,Population growth percent,Life expectancy in years,Death rate per 1000 people,Suicide mortality rate per 100000 population
5121,Iran,IRN,AS,1960,NaN,NaN,NaN,NaN,NaN,NaN,21.91,66.26,NaN,NaN,NaN,44.95,21.93,NaN
5122,Iran,IRN,AS,1961,13.3,NaN,NaN,NaN,NaN,NaN,22.48,65.61,NaN,NaN,2.58,45.51,21.27,NaN
5123,Iran,IRN,AS,1962,14.0,NaN,NaN,NaN,NaN,NaN,23.07,64.95,2000.0,NaN,2.59,46.07,20.63,NaN
5124,Iran,IRN,AS,1963,13.5,NaN,NaN,NaN,NaN,NaN,23.68,64.28,1500.0,NaN,2.61,46.62,19.99,NaN
5125,Iran,IRN,AS,1964,13.9,NaN,NaN,NaN,NaN,NaN,24.31,63.61,NaN,NaN,2.62,47.17,19.37,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5179,Iran,IRN,AS,2018,89.1,NaN,NaN,33.0,58.0,51.0,81.80,25.10,979435.0,NaN,1.39,76.48,4.84,5.7
5180,Iran,IRN,AS,2019,95.5,NaN,NaN,35.0,51.0,51.0,82.91,24.61,979435.0,NaN,1.35,76.68,4.84,5.2
5181,Iran,IRN,AS,2020,99.4,NaN,NaN,34.0,51.0,49.0,83.99,24.13,800025.0,NaN,1.29,76.87,4.84,NaN
5182,Iran,IRN,AS,2021,NaN,NaN,NaN,32.0,50.0,47.0,85.03,23.66,798343.0,NaN,1.23,NaN,NaN,NaN
5183,Iran,IRN,AS,2022,NaN,NaN,NaN,20.0,49.0,42.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [116]:
csv3[csv3['Country']=='Iran']

,Country,Code,ContinentCode,Year,Rule of law index (-2.5 weak; 2.5 strong),Government effectiveness index (-2.5 weak; 2.5 strong),Control of corruption (-2.5 weak; 2.5 strong),Regulatory quality index (-2.5 weak; 2.5 strong),Voice and accountability index (-2.5 weak; 2.5 strong),Political stability index (-2.5 weak; 2.5 strong),Corruption Perceptions Index 100 = no corruption,Political rights index 7 (weak) - 1 (strong),Civil liberties index 7 (weak) - 1 (strong),Shadow economy percent of GDP,Internet users percent of population,Mobile network coverage percent of the population,Gasoline prices at the pump in dollars per liter,Diesel prices at the pump in dollars per liter,Income from natural resources percent of GDP,Access to electricity percent of the population
3971,Iran,IRN,AS,1970,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.03,NaN
3972,Iran,IRN,AS,1971,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.08,NaN
3973,Iran,IRN,AS,1972,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,6.0,NaN,NaN,NaN,NaN,NaN,18.80,NaN
3974,Iran,IRN,AS,1973,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,6.0,NaN,NaN,NaN,NaN,NaN,20.13,NaN
3975,Iran,IRN,AS,1974,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,6.0,NaN,NaN,NaN,NaN,NaN,49.56,NaN
3976,Iran,IRN,AS,1975,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,6.0,NaN,NaN,NaN,NaN,NaN,38.56,NaN
3977,Iran,IRN,AS,1976,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,6.0,NaN,NaN,NaN,NaN,NaN,35.61,NaN
3978,Iran,IRN,AS,1977,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,5.0,NaN,NaN,NaN,NaN,NaN,30.69,NaN
3979,Iran,IRN,AS,1978,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,5.0,NaN,NaN,NaN,NaN,NaN,30.10,NaN
3980,Iran,IRN,AS,1979,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,5.0,NaN,NaN,NaN,NaN,NaN,34.13,NaN
3981,Iran,IRN,AS,1980,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,5.0,NaN,NaN,NaN,NaN,NaN,21.20,NaN
3982,Iran,IRN,AS,1981,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,6.0,NaN,NaN,NaN,NaN,NaN,14.68,NaN
3983,Iran,IRN,AS,1982,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,6.0,NaN,NaN,NaN,NaN,NaN,14.82,NaN
3984,Iran,IRN,AS,1983,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,6.0,NaN,NaN,NaN,NaN,NaN,13.56,NaN
3985,Iran,IRN,AS,1984,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,6.0,NaN,NaN,NaN,NaN,NaN,11.43,NaN
3986,Iran,IRN,AS,1985,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,6.0,NaN,NaN,NaN,NaN,NaN,10.29,NaN
3987,Iran,IRN,AS,1986,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,6.0,NaN,NaN,NaN,NaN,NaN,4.09,NaN
3988,Iran,IRN,AS,1987,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,6.0,NaN,NaN,NaN,NaN,NaN,9.82,NaN
3989,Iran,IRN,AS,1988,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,6.0,NaN,NaN,NaN,NaN,NaN,8.74,NaN
3990,Iran,IRN,AS,1989,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,5.0,NaN,NaN,NaN,NaN,NaN,15.56,NaN
3991,Iran,IRN,AS,1990,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,5.0,NaN,0.00,NaN,NaN,NaN,21.83,NaN
3992,Iran,IRN,AS,1991,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,5.0,19.13,0.00,NaN,NaN,NaN,NaN,NaN
3993,Iran,IRN,AS,1992,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,6.0,19.54,0.00,NaN,NaN,NaN,NaN,NaN
3994,Iran,IRN,AS,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,20.42,0.00,NaN,NaN,NaN,29.56,NaN
3995,Iran,IRN,AS,1994,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,20.85,0.00,NaN,NaN,NaN,24.57,NaN
3996,Iran,IRN,AS,1995,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,21.06,0.00,NaN,NaN,NaN,20.11,NaN
3997,Iran,IRN,AS,1996,-0.94,-0.60,-0.48,-1.42,-0.95,-0.32,NaN,6.0,7.0,20.65,0.02,NaN,NaN,NaN,20.35,NaN
3998,Iran,IRN,AS,1997,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,20.07,0.05,NaN,NaN,NaN,19.40,NaN
3999,Iran,IRN,AS,1998,-0.68,-0.49,-0.46,-1.62,-0.86,-0.69,NaN,6.0,6.0,20.35,0.10,NaN,0.08,0.01,12.66,NaN
4000,Iran,IRN,AS,1999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,6.0,19.88,0.38,NaN,NaN,NaN,17.91,NaN
4001,Iran,IRN,AS,2000,-0.52,-0.49,-0.40,-1.64,-0.93,-0.73,NaN,6.0,6.0,18.90,0.93,NaN,0.05,0.02,32.49,97.90
4002,Iran,IRN,AS,2001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,6.0,19.89,1.48,NaN,NaN,NaN,23.70,98.13
4003,Iran,IRN,AS,2002,-0.82,-0.62,-0.22,-1.32,-1.08,-0.77,NaN,6.0,6.0,18.39,4.63,NaN,0.07,0.02,22.00,98.23
4004,Iran,IRN,AS,2003,-0.68,-0.55,-0.31,-1.23,-1.25,-0.78,NaN,6.0,6.0,17.02,6.93,NaN,NaN,NaN,23.21,98.33
4005,Iran,IRN,AS,2004,-0.67,-0.49,-0.36,-1.27,-1.23,-0.76,29.0,6.0,6.0,16.01,7.49,NaN,0.09,0.02,26.66,98.43
4006,Iran,IRN,AS,2005,-0.87,-0.66,-0.48,-1.17,-1.28,-0.78,29.0,6.0,6.0,16.63,8.10,NaN,NaN,NaN,34.54,98.52
4007,Iran,IRN,AS,2006,-0.99,-0.54,-0.48,-1.42,-1.50,-1.04,27.0,6.0,6.0,16.34,8.76,NaN,0.09,0.03,34.77,98.40
4008,Iran,IRN,AS,2007,-1.03,-0.63,-0.56,-1.60,-1.55,-0.93,25.0,6.0,6.0,14.52,9.47,NaN,NaN,NaN,28.35,98.72
4009,Iran,IRN,AS,2008,-0.98,-0.67,-0.76,-1.61,-1.57,-0.94,23.0,6.0,6.0,14.60,12.02,NaN,0.10,0.03,33.22,98.83
4010,Iran,IRN,AS,2009,-1.05,-0.56,-0.77,-1.71,-1.58,-1.56,18.0,6.0,6.0,15.73,13.80,NaN,NaN,NaN,19.92,99.71
4011,Iran,IRN,AS,2010,-1.03,-0.48,-0.95,-1.71,-1.61,-1.63,22.0,6.0,6.0,15.60,15.90,NaN,0.10,0.02,23.05,99.49
4012,Iran,IRN,AS,2011,-0.97,-0.44,-0.88,-1.52,-1.58,-1.42,27.0,6.0,6.0,14.93,19.00,NaN,NaN,NaN,28.16,99.57
4013,Iran,IRN,AS,2012,-0.92,-0.53,-0.80,-1.43,-1.60,-1.32,28.0,6.0,6.0,15.79,22.73,95.0,0.33,0.12,23.39,99.64
4014,Iran,IRN,AS,2013,-1.00,-0.68,-0.69,-1.49,-1.61,-1.25,25.0,6.0,6.0,16.17,29.95,95.8,NaN,NaN,27.57,99.83
4015,Iran,IRN,AS,2014,-1.05,-0.43,-0.63,-1.46,-1.58,-0.87,27.0,6.0,6.0,16.14,39.35,96.0,0.37,0.19,27.47,100.00
4016,Iran,IRN,AS,2015,-0.92,-0.21,-0.61,-1.31,-1.51,-0.93,27.0,6.0,6.0,18.38,45.33,96.0,NaN,NaN,15.80,99.96
4017,Iran,IRN,AS,2016,-0.68,-0.19,-0.72,-1.23,-1.34,-0.81,29.0,6.0,6.0,NaN,53.23,94.2,0.40,0.22,13.66,99.95
4018,Iran,IRN,AS,2017,-0.69,-0.20,-0.82,-1.20,-1.30,-0.93,30.0,6.0,6.0,NaN,64.04,NaN,NaN,NaN,18.08,99.94
4019,Iran,IRN,AS,2018,-0.70,-0.43,-0.96,-1.38,-1.33,-1.35,28.0,6.0,6.0,NaN,70.20,NaN,NaN,NaN,36.04,100.00
4020,Iran,IRN,AS,2019,-0.75,-0.56,-1.05,-1.43,-1.39,-1.71,26.0,6.0,6.0,NaN,77.77,NaN,NaN,NaN,26.71,100.00
4021,Iran,IRN,AS,2020,-0.87,-0.99,-1.09,-1.47,-1.48,-1.70,25.0,6.0,6.0,NaN,84.11,NaN,NaN,NaN,22.34,100.00
4022,Iran,IRN,AS,2021,-0.95,-0.86,-1.10,-1.62,-1.47,-1.62,25.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [96]:
csv_full

,Country_x,Code_x,ContinentCode_x,Year_x,Military spending percent of total government spending,Arms imports million constant U.S. dollars,Cost of living index world average = 100,Food price index world average = 100,Housing and utilities price index world average = 100,Healthcare price index world average = 100,...,Group grievance index 0 (low) - 10 (high),Economic decline index 0 (low) - 10 (high),Uneven economic development index 0 (low) - 10 (high),State legitimacy index 0 (high) - 10 (low),Human rights and rule of law index 0 (high) - 10 (low),Demographic pressures 0 (low) - 10 (high),Refugees and displaced persons index 0 (low) - 10 (high),External interventions index 0 (low) - 10 (high),conflict_id,Year
0,Afghanistan,AFG,AS,1960.0,NaN,40.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
1,Afghanistan,AFG,AS,1961.0,NaN,56.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
2,Afghanistan,AFG,AS,1962.0,NaN,64.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
3,Afghanistan,AFG,AS,1963.0,NaN,40.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
4,Afghanistan,AFG,AS,1964.0,NaN,56.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12559,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
12560,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,Taiwan1969
12561,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,Taiwan1970
12562,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,Taiwan1971
12563,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.1,9.9,8.0,9.9,9.9,9.9,9.9,9.4,0,Yemen2022

In [47]:
my_list = []

for index, row in conflicts.iterrows():
    temp = csv_full[(csv_full['CountryYear'] == row['Country']+str(row['Year -1'])) | 
             (csv_full['CountryYear'] == row['Country']+str(row['Year -2'])) |(csv_full['CountryYear'] == row['Country']+str(row['Year -3'])) 
             |(csv_full['CountryYear'] == row['Country']+str(row['Year -4'])) |(csv_full['CountryYear'] == row['Country']+str(row['Year -5'])) ]
    
    my_list.append(temp)

In [169]:

csv_iran22 = csv_full[(csv_full['CountryYear'] == 'Iran2017') | (csv_full['CountryYear'] == 'Iran2018') |(csv_full['CountryYear'] == 'Iran2019') |(csv_full['CountryYear'] == 'Iran2020') |(csv_full['CountryYear'] == 'Iran2021') ]
csv_iran22.isna().sum()[0:20]

#csv1[csv1['Country']=='Iran'].tail(5)

Country_x                                                  0
Code_x                                                     0
ContinentCode_x                                            0
Year_x                                                     0
Military spending percent of total government spending     1
Arms imports million constant U.S. dollars                 1
Cost of living index world average = 100                   4
Food price index world average = 100                       4
Housing and utilities price index world average  = 100     4
Healthcare price index world average = 100                 4
Happiness Index 0 (unhappy) - 10 (happy)                   0
Human Development Index (0 - 1)                            1
CountryYear                                                0
Country_y                                                  0
Code_y                                                     0
ContinentCode_y                                            0
Year_y                                                     0
Economic growth: the rate of change of real GDP            1
GDP per capita current U.S. dollars                        1
GDP per capita Purchasing Power Parity                     1
dtype: int64

In [48]:
for i in range(len(my_list)):
    my_list[i]['conflict_id'] = i

/var/folders/_s/vshzgsh90qdgm6zwx2gfmpv80000gn/T/ipykernel_70562/729059741.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  my_list[i]['conflict_id'] = i

In [175]:
csv_full[csv_full['CountryYear']=='Zimbabwe2021']

,Country_x,Code_x,ContinentCode_x,Year_x,Military spending percent of total government spending,Arms imports million constant U.S. dollars,Cost of living index world average = 100,Food price index world average = 100,Housing and utilities price index world average = 100,Healthcare price index world average = 100,...,Security threats index 0 (low) - 10 (high),Factionalized elites index 0 (low) - 10 (high),Group grievance index 0 (low) - 10 (high),Economic decline index 0 (low) - 10 (high),Uneven economic development index 0 (low) - 10 (high),State legitimacy index 0 (high) - 10 (low),Human rights and rule of law index 0 (high) - 10 (low),Demographic pressures 0 (low) - 10 (high),Refugees and displaced persons index 0 (low) - 10 (high),External interventions index 0 (low) - 10 (high)
8767,Zimbabwe,ZWE,AF,2021.0,NaN,NaN,NaN,NaN,NaN,NaN,...,8.6,10.0,6.1,9.4,7.7,8.8,8.0,9.3,8.2,6.9

In [11]:
for i in range(len(my_list)):
    if len(my_list[i]) < 5:
        print(i)

111

In [97]:
final_df = pd.DataFrame(columns=my_list[100].columns)

In [98]:
final_df

Empty DataFrame
Columns: [Country_x, Code_x, ContinentCode_x, Year_x, Military spending percent of total government spending , Arms imports million constant U.S. dollars, Cost of living index world average = 100, Food price index world average = 100, Housing and utilities price index world average  = 100, Healthcare price index world average = 100, Happiness Index 0 (unhappy) - 10 (happy), Human Development Index (0 - 1), CountryYear, Country_y, Code_y, ContinentCode_y, Year_y, Economic growth: the rate of change of real GDP, GDP per capita current U.S. dollars, GDP per capita Purchasing Power Parity, Capital investment as percent of GDP, Inflation: percent change in the Consumer Price Index, Unemployment rate, Youth unemployment ages 15-24, Labor force participation rate, Trade openness: exports plus imports as percent of GDP, Foreign Direct Investment percent of GDP, Trade balance as percent of GDP, External debt percent of Gross National Income, Government spending as percent of GDP, Fiscal balance percent of GDP, Government debt as percent of GDP, Foreign aid and official development assistance received, Country_x, Code_x, ContinentCode_x, Year_x, Rule of law index (-2.5 weak; 2.5 strong), Government effectiveness index (-2.5 weak; 2.5 strong), Control of corruption (-2.5 weak; 2.5 strong), Regulatory quality index (-2.5 weak; 2.5 strong), Voice and accountability index (-2.5 weak; 2.5 strong), Political stability index (-2.5 weak; 2.5 strong), Corruption Perceptions Index 100 = no corruption, Political rights index 7 (weak) - 1 (strong), Civil liberties index 7 (weak) - 1 (strong) , Shadow economy percent of GDP, Internet users percent of population, Mobile network coverage percent of the population, Gasoline prices at the pump in dollars per liter, Diesel prices at the pump in dollars per liter, Income from natural resources percent of GDP, Access to electricity percent of the population, Country_y, Code_y, ContinentCode_y, Year_y, Food production index (2004-2006 = 100), Banking system z-scores, Real interest rate: Bank lending rate minus inflation, Freedom from corruption index (0-100), Labor freedom index (0-100), Economic freedom overall index (0-100), Population size in millions, Rural population percent of total population, Refugee population, Migrant population percent of total population, Population growth percent, Life expectancy in years, Death rate per 1000 people, Suicide mortality rate per 100000 population, Country_x, Code_x, ContinentCode_x, Year_x, Deaths of children under five years of age per 1000 live births, Doctors per 1000 people, Gini income inequality index, Poverty percent of population, Poverty ratio percent living on less than 1.90 USD a day, Poverty ratio percent living on less than 5.50 USD a day, Percent income earned by the top 10 percent of earners, Public spending on education percent of GDP, Literacy rate, Globalization index (0-100), Economic globalization index (0-100), Political globalization index (0-100), Social globalization index (0-100), Number of prisoners per 100000 people, Homicides per 100000 people, Country_y, Code_y, ContinentCode_y, Year_y, People practicing Judaism as percent of the population, Buddhists as percent of the total population, People practicing Hinduism as percent of the population, Shia Muslims as percent of the total population, Sunni Muslims as percent of the total population, Christians as percent of the total population, ...]
Index: []

[0 rows x 115 columns]

In [99]:
for i in range(len(my_list)):
    
    final_df = pd.concat([final_df,my_list[i]])

In [69]:
final_df

,Military spending percent of total government spending,Arms imports million constant U.S. dollars,Human Development Index (0 - 1),Economic growth: the rate of change of real GDP,GDP per capita current U.S. dollars,GDP per capita Purchasing Power Parity,Capital investment as percent of GDP,Inflation: percent change in the Consumer Price Index,Unemployment rate,Youth unemployment ages 15-24,...,Factionalized elites index 0 (low) - 10 (high),Group grievance index 0 (low) - 10 (high),Economic decline index 0 (low) - 10 (high),Uneven economic development index 0 (low) - 10 (high),State legitimacy index 0 (high) - 10 (low),Human rights and rule of law index 0 (high) - 10 (low),Demographic pressures 0 (low) - 10 (high),Refugees and displaced persons index 0 (low) - 10 (high),External interventions index 0 (low) - 10 (high),conflict_id
4437,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4438,NaN,49.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4439,NaN,41.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4440,NaN,28.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
9937,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4163,3.45,214.0,0.813,4.1,9247.58,24862.97,26.35,7.4,4.90,3.78,...,7.6,7.6,6.4,4.2,8.3,7.3,4.5,3.0,4.2,110
4164,4.65,310.0,0.817,4.1,9812.63,25544.35,25.26,6.0,4.85,3.84,...,7.6,7.9,5.9,3.9,8.4,7.0,4.2,2.7,3.9,110
4165,5.25,312.0,0.817,4.5,9812.60,26351.80,27.63,5.2,4.80,3.89,...,7.6,8.1,5.6,3.6,8.5,6.7,3.9,2.4,3.6,110
4166,4.56,268.0,0.825,-2.5,9121.64,25361.51,28.52,6.7,4.89,3.76,...,7.6,8.2,5.3,3.3,8.5,6.4,3.6,2.3,3.3,110
4167,NaN,NaN,NaN,4.0,10041.49,26033.24,NaN,NaN,4.90,3.73,...,7.6,8.0,5.5,3.2,8.2,6.7,4.1,2.1,3.0,110

In [68]:
my_list[0].iloc[[4]]['CountryYear']

9937    Lebanon1970
Name: CountryYear, dtype: object

# Dropping features

In [100]:
final_df.shape

(555, 115)

In [101]:
to_drop  = pd.DataFrame(final_df.isna().sum()/555)
len(to_drop)

115

In [102]:
to_drop_list = to_drop[to_drop[0]>0.7].index.values.tolist()
to_drop_list

['Cost of living index world average = 100',
 'Food price index world average = 100',
 'Housing and utilities price index world average  = 100',
 'Healthcare price index world average = 100',
 'Happiness Index 0 (unhappy) - 10 (happy)',
 'Mobile network coverage percent of the population',
 'Gasoline prices at the pump in dollars per liter',
 'Diesel prices at the pump in dollars per liter',
 'Migrant population percent of total population',
 'Doctors per 1000 people',
 'Gini income inequality index',
 'Poverty percent of population',
 'Poverty ratio percent living on less than 1.90 USD a day',
 'Poverty ratio percent living on less than 5.50 USD a day',
 'Percent income earned by the top 10 percent of earners',
 'Literacy rate',
 'Number of prisoners per 100000 people',
 'People practicing Judaism as percent of the population',
 'Buddhists as percent of the total population',
 'People practicing Hinduism as percent of the population',
 'Shia Muslims as percent of the total population',
 'Catholic Christians as percent of the total population',
 'Protestant Christians as percent of the total population',
 'Eastern Orthodox Christians as percent of the total population',
 'Non religious people as percent of the population']

In [103]:
for i in to_drop_list:
    final_df.drop(columns=i, axis=1, inplace=True)

In [106]:
final_df['CountryYear']

4437       Lebanon1971
4438       Lebanon1972
4439       Lebanon1973
4440       Lebanon1974
9937       Lebanon1970
             ...
4163    Kazakhstan2017
4164    Kazakhstan2018
4165    Kazakhstan2019
4166    Kazakhstan2020
4167    Kazakhstan2021
Name: CountryYear, Length: 555, dtype: object

# Grouping

In [20]:
grouped_df = final_df.groupby(by='conflict_id').mean()

/var/folders/_s/vshzgsh90qdgm6zwx2gfmpv80000gn/T/ipykernel_70344/708265669.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  grouped_df = final_df.groupby(by='conflict_id').mean()

In [21]:
grouped_df

,Year_x,Military spending percent of total government spending,Arms imports million constant U.S. dollars,Cost of living index world average = 100,Food price index world average = 100,Housing and utilities price index world average = 100,Healthcare price index world average = 100,Happiness Index 0 (unhappy) - 10 (happy),Human Development Index (0 - 1),Year_y,...,Security threats index 0 (low) - 10 (high),Factionalized elites index 0 (low) - 10 (high),Group grievance index 0 (low) - 10 (high),Economic decline index 0 (low) - 10 (high),Uneven economic development index 0 (low) - 10 (high),State legitimacy index 0 (high) - 10 (low),Human rights and rule of law index 0 (high) - 10 (low),Demographic pressures 0 (low) - 10 (high),Refugees and displaced persons index 0 (low) - 10 (high),External interventions index 0 (low) - 10 (high)
conflict_id,,,,,,,,,,,,,,,,,,,,,
0,1972.5,NaN,31.250000,NaN,NaN,NaN,NaN,NaN,NaN,1972.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1972.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1974.0,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,1972.25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1973.0,NaN,49.400000,NaN,NaN,NaN,NaN,NaN,NaN,1973.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1976.0,NaN,131.666667,NaN,NaN,NaN,NaN,NaN,NaN,1975.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,2019.0,5.4475,44.500000,83.26,100.450,88.872,59.47,5.696,0.76275,2019.00,...,6.58,7.10,8.00,3.68,6.84,7.00,3.78,6.20,4.06,2.90
107,2019.0,6.2275,12.750000,82.35,103.177,54.991,67.88,5.860,0.75800,2019.00,...,6.32,8.20,6.70,5.88,6.38,6.02,4.36,6.10,5.62,5.70
108,2019.0,NaN,76.666667,NaN,NaN,NaN,NaN,6.096,0.71175,2019.00,...,6.74,8.80,6.58,5.82,6.28,9.44,8.20,5.14,4.98,4.22
109,2019.0,10.2375,68.000000,52.19,85.113,32.959,19.65,4.394,0.77950,2019.00,...,7.04,8.98,8.88,5.44,6.50,6.66,8.28,6.06,7.80,6.06
110,2019.0,4.4775,276.000000,55.08,70.570,63.413,30.55,5.960,0.81800,2019.00,...,4.60,7.60,7.96,5.74,3.64,8.38,6.82,4.06,2.50,3.60

# Dropping data for the imputer

In [57]:
bin_list = ['Country_x', 'Code_x', 'ContinentCode_x', 'Year_x','CountryYear', 'Country_y', 'Code_y','ContinentCode_y', 'Year_y','Country_x',
       'Code_x', 'ContinentCode_x', 'Year_x','Country_y',
       'Code_y', 'ContinentCode_y', 'Year_y','Country_x', 'Sunni Muslims as percent of the total population','Code_x',
       'ContinentCode_x', 'Year_x','Country_y', 'Code_y', 'ContinentCode_y', 'Year_y','Christians as percent of the total population',]

In [58]:
cleaner_df = final_df.drop(columns=bin_list)

,Military spending percent of total government spending,Arms imports million constant U.S. dollars,Human Development Index (0 - 1),Economic growth: the rate of change of real GDP,GDP per capita current U.S. dollars,GDP per capita Purchasing Power Parity,Capital investment as percent of GDP,Inflation: percent change in the Consumer Price Index,Unemployment rate,Youth unemployment ages 15-24,...,Factionalized elites index 0 (low) - 10 (high),Group grievance index 0 (low) - 10 (high),Economic decline index 0 (low) - 10 (high),Uneven economic development index 0 (low) - 10 (high),State legitimacy index 0 (high) - 10 (low),Human rights and rule of law index 0 (high) - 10 (low),Demographic pressures 0 (low) - 10 (high),Refugees and displaced persons index 0 (low) - 10 (high),External interventions index 0 (low) - 10 (high),conflict_id
4437,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4438,NaN,49.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4439,NaN,41.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4440,NaN,28.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
9937,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4163,3.45,214.0,0.813,4.1,9247.58,24862.97,26.35,7.4,4.90,3.78,...,7.6,7.6,6.4,4.2,8.3,7.3,4.5,3.0,4.2,110
4164,4.65,310.0,0.817,4.1,9812.63,25544.35,25.26,6.0,4.85,3.84,...,7.6,7.9,5.9,3.9,8.4,7.0,4.2,2.7,3.9,110
4165,5.25,312.0,0.817,4.5,9812.60,26351.80,27.63,5.2,4.80,3.89,...,7.6,8.1,5.6,3.6,8.5,6.7,3.9,2.4,3.6,110
4166,4.56,268.0,0.825,-2.5,9121.64,25361.51,28.52,6.7,4.89,3.76,...,7.6,8.2,5.3,3.3,8.5,6.4,3.6,2.3,3.3,110
4167,NaN,NaN,NaN,4.0,10041.49,26033.24,NaN,NaN,4.90,3.73,...,7.6,8.0,5.5,3.2,8.2,6.7,4.1,2.1,3.0,110

In [60]:
cleaner_df['conflict_id']=cleaner_df['conflict_id'].astype(int)

In [61]:
cleaner_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 555 entries, 4437 to 4167
Data columns (total 63 columns):
 #   Column                                                           Non-Null Count  Dtype
---  ------                                                           --------------  -----
 0   Military spending percent of total government spending           310 non-null    float64
 1   Arms imports million constant U.S. dollars                       377 non-null    float64
 2   Human Development Index (0 - 1)                                  391 non-null    float64
 3   Economic growth: the rate of change of real GDP                  487 non-null    float64
 4   GDP per capita current U.S. dollars                              486 non-null    float64
 5   GDP per capita Purchasing Power Parity                           365 non-null    float64
 6   Capital investment as percent of GDP                             442 non-null    float64
 7   Inflation: percent change in the Consumer Price Index            435 non-null    float64
 8   Unemployment rate                                                396 non-null    float64
 9   Youth unemployment ages 15-24                                    396 non-null    float64
 10  Labor force participation rate                                   409 non-null    float64
 11  Trade openness: exports plus imports as percent of GDP           447 non-null    float64
 12  Foreign Direct Investment percent of GDP                         475 non-null    float64
 13  Trade balance as percent of GDP                                  450 non-null    float64
 14  External debt percent of Gross National Income                   405 non-null    float64
 15  Government spending as percent of GDP                            425 non-null    float64
 16  Fiscal balance percent of GDP                                    336 non-null    float64
 17  Government debt as percent of GDP                                304 non-null    float64
 18  Foreign aid and official development assistance received         496 non-null    float64
 19  Rule of law index (-2.5 weak; 2.5 strong)                        320 non-null    float64
 20  Government effectiveness index (-2.5 weak; 2.5 strong)           320 non-null    float64
 21  Control of corruption (-2.5 weak; 2.5 strong)                    320 non-null    float64
 22  Regulatory quality index (-2.5 weak; 2.5 strong)                 320 non-null    float64
 23  Voice and accountability index (-2.5 weak; 2.5 strong)           320 non-null    float64
 24  Political stability index (-2.5 weak; 2.5 strong)                320 non-null    float64
 25  Corruption Perceptions Index 100 = no corruption                 274 non-null    float64
 26  Political rights index 7 (weak) - 1 (strong)                     510 non-null    float64
 27  Civil liberties index 7 (weak) - 1 (strong)                      515 non-null    float64
 28  Shadow economy percent of GDP                                    250 non-null    float64
 29  Internet users percent of population                             399 non-null    float64
 30  Income from natural resources percent of GDP                     477 non-null    float64
 31  Access to electricity percent of the population                  335 non-null    float64
 32  Food production index (2004-2006 = 100)                          528 non-null    float64
 33  Banking system z-scores                                          268 non-null    float64
 34  Real interest rate: Bank lending rate minus inflation            262 non-null    float64
 35  Freedom from corruption index (0-100)                            317 non-null    float64
 36  Labor freedom index (0-100)                                      266 non-null    float64
 37  Economic freedom overall index (0-100)                           303 non-null    float64
 38  Population size in millions                                      550 non-null    float64
 39  Rural population percent of total population                     550 non-null    float64
 40  Refugee population                                               452 non-null    float64
 41  Population growth percent                                        550 non-null    float64
 42  Life expectancy in years                                         543 non-null    float64
 43  Death rate per 1000 people                                       543 non-null    float64
 44  Suicide mortality rate per 100000 population                     291 non-null    float64
 45  Deaths of children under five years of age per 1000 live births  532 non-null    float64
 46  Public spending on education percent of GDP                      266 non-null    float64
 47  Globalization index (0-100)                                      499 non-null    float64
 48  Economic globalization index (0-100)                             490 non-null    float64
 49  Political globalization index (0-100)                            509 non-null    float64
 50  Social globalization index (0-100)                               509 non-null    float64
 51  Homicides per 100000 people                                      175 non-null    float64
 52  Security threats index 0 (low) - 10 (high)                       264 non-null    float64
 53  Factionalized elites index 0 (low) - 10 (high)                   264 non-null    float64
 54  Group grievance index 0 (low) - 10 (high)                        264 non-null    float64
 55  Economic decline index 0 (low) - 10 (high)                       264 non-null    float64
 56  Uneven economic development index 0 (low) - 10 (high)            264 non-null    float64
 57  State legitimacy index 0 (high) - 10 (low)                       264 non-null    float64
 58  Human rights and rule of law index 0 (high) - 10 (low)           264 non-null    float64
 59  Demographic pressures 0 (low) - 10 (high)                        264 non-null    float64
 60  Refugees and displaced persons index 0 (low) - 10 (high)         264 non-null    float64
 61  External interventions index 0 (low) - 10 (high)                 264 non-null    float64
 62  conflict_id                                                      555 non-null    int64
dtypes: float64(62), int64(1)
memory usage: 277.5 KB

# Grouping the data

In [72]:
grouped_df = cleaner_df.groupby(by='conflict_id').mean()

In [73]:
grouped_df

,Military spending percent of total government spending,Arms imports million constant U.S. dollars,Human Development Index (0 - 1),Economic growth: the rate of change of real GDP,GDP per capita current U.S. dollars,GDP per capita Purchasing Power Parity,Capital investment as percent of GDP,Inflation: percent change in the Consumer Price Index,Unemployment rate,Youth unemployment ages 15-24,...,Security threats index 0 (low) - 10 (high),Factionalized elites index 0 (low) - 10 (high),Group grievance index 0 (low) - 10 (high),Economic decline index 0 (low) - 10 (high),Uneven economic development index 0 (low) - 10 (high),State legitimacy index 0 (high) - 10 (low),Human rights and rule of law index 0 (high) - 10 (low),Demographic pressures 0 (low) - 10 (high),Refugees and displaced persons index 0 (low) - 10 (high),External interventions index 0 (low) - 10 (high)
conflict_id,,,,,,,,,,,,,,,,,,,,,
0,NaN,31.250000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,49.400000,NaN,7.000,147.340,NaN,17.918,20.280,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,131.666667,NaN,NaN,184.996,NaN,10.382,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,5.4475,44.500000,0.76275,2.226,6700.366,12416.858,20.810,2.620,4.514,9.702,...,6.58,7.10,8.00,3.68,6.84,7.00,3.78,6.20,4.06,2.90
107,6.2275,12.750000,0.75800,0.024,6058.920,11097.980,24.668,0.060,4.744,10.090,...,6.32,8.20,6.70,5.88,6.38,6.02,4.36,6.10,5.62,5.70
108,NaN,76.666667,0.71175,4.954,1806.112,7270.168,37.868,NaN,6.338,14.324,...,6.74,8.80,6.58,5.82,6.28,9.44,8.20,5.14,4.98,4.22
109,10.2375,68.000000,0.77950,1.844,3898.644,12784.654,28.120,5.300,4.798,22.266,...,7.04,8.98,8.88,5.44,6.50,6.66,8.28,6.06,7.80,6.06
110,4.4775,276.000000,0.81800,2.840,9607.188,25630.774,26.940,6.325,4.868,3.800,...,4.60,7.60,7.96,5.74,3.64,8.38,6.82,4.06,2.50,3.60

# Imputer (on final_df)

In [40]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

In [226]:
imputer = IterativeImputer(max_iter=10, random_state=0, missing_values=np.nan)

numerics = ['int16', 'int32', 'int64', 'float16', 'float32', 'float64']
data_numeric = grouped_df.select_dtypes(include=numerics)
imputed_final_df = pd.DataFrame(imputer.fit_transform(data_numeric), columns=grouped_df.columns)

,Military spending percent of total government spending,Arms imports million constant U.S. dollars,Human Development Index (0 - 1),Economic growth: the rate of change of real GDP,GDP per capita current U.S. dollars,GDP per capita Purchasing Power Parity,Capital investment as percent of GDP,Inflation: percent change in the Consumer Price Index,Unemployment rate,Youth unemployment ages 15-24,...,Security threats index 0 (low) - 10 (high),Factionalized elites index 0 (low) - 10 (high),Group grievance index 0 (low) - 10 (high),Economic decline index 0 (low) - 10 (high),Uneven economic development index 0 (low) - 10 (high),State legitimacy index 0 (high) - 10 (low),Human rights and rule of law index 0 (high) - 10 (low),Demographic pressures 0 (low) - 10 (high),Refugees and displaced persons index 0 (low) - 10 (high),External interventions index 0 (low) - 10 (high)
conflict_id,,,,,,,,,,,,,,,,,,,,,
0,NaN,31.250000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,49.400000,NaN,7.000,147.340,NaN,17.918,20.280,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,131.666667,NaN,NaN,184.996,NaN,10.382,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,5.4475,44.500000,0.76275,2.226,6700.366,12416.858,20.810,2.620,4.514,9.702,...,6.58,7.10,8.00,3.68,6.84,7.00,3.78,6.20,4.06,2.90
107,6.2275,12.750000,0.75800,0.024,6058.920,11097.980,24.668,0.060,4.744,10.090,...,6.32,8.20,6.70,5.88,6.38,6.02,4.36,6.10,5.62,5.70
108,NaN,76.666667,0.71175,4.954,1806.112,7270.168,37.868,NaN,6.338,14.324,...,6.74,8.80,6.58,5.82,6.28,9.44,8.20,5.14,4.98,4.22
109,10.2375,68.000000,0.77950,1.844,3898.644,12784.654,28.120,5.300,4.798,22.266,...,7.04,8.98,8.88,5.44,6.50,6.66,8.28,6.06,7.80,6.06
110,4.4775,276.000000,0.81800,2.840,9607.188,25630.774,26.940,6.325,4.868,3.800,...,4.60,7.60,7.96,5.74,3.64,8.38,6.82,4.06,2.50,3.60

In [75]:
imputed_final_df

,Military spending percent of total government spending,Arms imports million constant U.S. dollars,Human Development Index (0 - 1),Economic growth: the rate of change of real GDP,GDP per capita current U.S. dollars,GDP per capita Purchasing Power Parity,Capital investment as percent of GDP,Inflation: percent change in the Consumer Price Index,Unemployment rate,Youth unemployment ages 15-24,...,Security threats index 0 (low) - 10 (high),Factionalized elites index 0 (low) - 10 (high),Group grievance index 0 (low) - 10 (high),Economic decline index 0 (low) - 10 (high),Uneven economic development index 0 (low) - 10 (high),State legitimacy index 0 (high) - 10 (low),Human rights and rule of law index 0 (high) - 10 (low),Demographic pressures 0 (low) - 10 (high),Refugees and displaced persons index 0 (low) - 10 (high),External interventions index 0 (low) - 10 (high)
0,10.217997,31.250000,0.627817,3.268683,3391.388883,9643.414445,22.191836,361.789211,8.132514,14.702224,...,7.269192,8.101811,7.393843,9.245497,7.088812,8.050250,7.652044,9.619116,6.288507,9.974898
1,10.323340,98.887485,0.157038,2.834024,3328.984423,9334.821861,21.390208,525.791875,7.460086,14.342174,...,7.390005,8.165236,7.512811,13.024003,7.202554,8.166873,7.718671,13.514038,6.420715,13.896155
2,10.339541,1.000000,0.228865,2.569179,3280.612585,9278.681012,21.332871,650.870536,7.519319,14.066870,...,7.392796,8.169775,7.502238,13.431004,7.233264,8.196895,7.742796,14.023744,6.446181,14.454944
3,10.210426,49.400000,0.351347,7.000000,147.340000,3696.294173,17.918000,20.280000,7.845915,14.333652,...,7.888622,8.661197,7.792475,8.257711,7.448522,8.294120,8.048644,9.199787,7.088402,8.771053
4,10.620474,131.666667,0.139096,3.509695,184.996000,3654.544997,10.382000,586.293379,8.963261,15.272556,...,7.964243,8.743174,7.878510,14.186021,7.565756,8.566689,8.123752,14.479573,7.109040,15.293051
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,5.447500,44.500000,0.762750,2.226000,6700.366000,12416.858000,20.810000,2.620000,4.514000,9.702000,...,6.580000,7.100000,8.000000,3.680000,6.840000,7.000000,3.780000,6.200000,4.060000,2.900000
107,6.227500,12.750000,0.758000,0.024000,6058.920000,11097.980000,24.668000,0.060000,4.744000,10.090000,...,6.320000,8.200000,6.700000,5.880000,6.380000,6.020000,4.360000,6.100000,5.620000,5.700000
108,9.122637,76.666667,0.711750,4.954000,1806.112000,7270.168000,37.868000,-97.933434,6.338000,14.324000,...,6.740000,8.800000,6.580000,5.820000,6.280000,9.440000,8.200000,5.140000,4.980000,4.220000
109,10.237500,68.000000,0.779500,1.844000,3898.644000,12784.654000,28.120000,5.300000,4.798000,22.266000,...,7.040000,8.980000,8.880000,5.440000,6.500000,6.660000,8.280000,6.060000,7.800000,6.060000
110,4.477500,276.000000,0.818000,2.840000,9607.188000,25630.774000,26.940000,6.325000,4.868000,3.800000,...,4.600000,7.600000,7.960000,5.740000,3.640000,8.380000,6.820000,4.060000,2.500000,3.600000

# Create the control dataset

In [107]:
conflict_years = final_df['CountryYear']

In [217]:
csv4_after_1980 = csv4[csv4['Year'] > 1975]
csv4_after_1980_noconflict = csv4_after_1980[csv4_after_1980.CountryYear.isin(conflict_years)==False]
csv4_after_1980.shape[0] - csv4_after_1980_noconflict.shape[0]
control_sample = csv4_after_1980.sample(110)[['CountryYear']]

In [218]:
control_sample

def slice_fn(sample):
    year = int(sample[-4:])
    words = [sample[:-4]+str(year-i-1) for i in range(4)]
    words.append(sample)
    return words

full_list = []

for index, row in control_sample.iterrows():
    full_list.append(slice_fn(row['CountryYear']))

In [219]:
from itertools import chain

samples = list(chain(*full_list))

sample_full = csv_full[csv_full.CountryYear.isin(samples)==True]
sample_full

,Country_x,Code_x,ContinentCode_x,Year_x,Military spending percent of total government spending,Arms imports million constant U.S. dollars,Cost of living index world average = 100,Food price index world average = 100,Housing and utilities price index world average = 100,Healthcare price index world average = 100,...,Group grievance index 0 (low) - 10 (high),Economic decline index 0 (low) - 10 (high),Uneven economic development index 0 (low) - 10 (high),State legitimacy index 0 (high) - 10 (low),Human rights and rule of law index 0 (high) - 10 (low),Demographic pressures 0 (low) - 10 (high),Refugees and displaced persons index 0 (low) - 10 (high),External interventions index 0 (low) - 10 (high),conflict_id,Year
79,Albania,ALB,EU,1980.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
183,Andorra,AND,EU,2010.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
184,Andorra,AND,EU,2011.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
185,Andorra,AND,EU,2012.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
186,Andorra,AND,EU,2013.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11936,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
11937,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
11938,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
12190,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.8,7.1,8.5,5.8,6.6,7.7,4.6,5.3,0,NaN
12485,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.8,6.5,2.9,6.5,5.8,4.8,4.2,7.5,0,NaN

In [205]:
sample_full['conflict_id'] = 0

/var/folders/_s/vshzgsh90qdgm6zwx2gfmpv80000gn/T/ipykernel_70562/2944837250.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample_full['conflict_id'] = 0

In [206]:
id_list = list(range(111,221))*5

In [209]:
id_list = sorted(id_list)

In [221]:
sample_full['conflict_id'] = id_list

/var/folders/_s/vshzgsh90qdgm6zwx2gfmpv80000gn/T/ipykernel_70562/3667711497.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample_full['conflict_id'] = id_list

(550, 116)

In [222]:
control_groupedby = sample_full.groupby('conflict_id').mean()

/var/folders/_s/vshzgsh90qdgm6zwx2gfmpv80000gn/T/ipykernel_70562/3478027142.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  control_groupedby = sample_full.groupby('conflict_id').mean()

In [298]:
columns_to_keep = list(imputed_final_df.columns)

In [300]:
sample_full_clean = control_groupedby.drop(columns=[col for col in control_groupedby if col not in columns_to_keep])

sample_full_clean.isna().sum()

Military spending percent of total government spending      44
Arms imports million constant U.S. dollars                  33
Human Development Index (0 - 1)                             28
Economic growth: the rate of change of real GDP              8
GDP per capita current U.S. dollars                          3
                                                            ..
State legitimacy index 0 (high) - 10 (low)                  65
Human rights and rule of law index 0 (high) - 10 (low)      65
Demographic pressures 0 (low) - 10 (high)                   65
Refugees and displaced persons index 0 (low) - 10 (high)    65
External interventions index 0 (low) - 10 (high)            65
Length: 62, dtype: int64

# Imputing control

In [229]:
imputed_control = pd.DataFrame(imputer.fit_transform(sample_full_clean), columns=sample_full_clean.columns)
imputed_control

,Military spending percent of total government spending,Arms imports million constant U.S. dollars,Human Development Index (0 - 1),Economic growth: the rate of change of real GDP,GDP per capita current U.S. dollars,GDP per capita Purchasing Power Parity,Capital investment as percent of GDP,Inflation: percent change in the Consumer Price Index,Unemployment rate,Youth unemployment ages 15-24,...,Security threats index 0 (low) - 10 (high),Factionalized elites index 0 (low) - 10 (high),Group grievance index 0 (low) - 10 (high),Economic decline index 0 (low) - 10 (high),Uneven economic development index 0 (low) - 10 (high),State legitimacy index 0 (high) - 10 (low),Human rights and rule of law index 0 (high) - 10 (low),Demographic pressures 0 (low) - 10 (high),Refugees and displaced persons index 0 (low) - 10 (high),External interventions index 0 (low) - 10 (high)
0,4.292091,209.322106,0.790600,-2.625000,40601.665000,51634.628689,35.810000,84.564378,9.634465,21.852287,...,3.303738,4.552520,4.725486,3.562728,4.191069,2.974549,1.353090,5.025372,3.488201,3.154603
1,6.030000,69.500000,0.853000,1.680000,8598.414000,4032.150000,22.532515,2284.975000,4.150000,8.892500,...,6.180200,11.042710,6.053335,6.854513,6.672058,-10.885526,1.448891,19.597985,4.853890,5.455294
2,8.609929,363.800000,0.647129,2.118000,2154.510000,9188.155848,28.954000,108.821431,8.782994,19.040874,...,5.596149,7.884200,6.126349,6.188445,6.106055,7.659240,6.542294,8.028683,4.600025,5.923024
3,5.760000,93.000000,0.723600,5.654000,6883.974000,16839.540000,17.900000,166.338771,10.492000,22.108000,...,5.321433,7.562185,6.034932,5.873138,5.889429,5.930206,5.612593,8.378061,4.560561,5.797720
4,12.438000,3.000000,0.626400,7.120000,541.122000,3429.844000,28.754000,3.200000,9.976000,19.042000,...,6.000174,7.478919,6.275339,6.635955,6.568458,9.459550,8.990200,7.660674,4.736830,5.697834
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105,8.118152,170.124299,0.665829,0.740000,3584.640000,3486.083333,22.662126,182.482990,6.909514,10.333058,...,5.876329,7.248924,6.067586,6.552788,6.471974,5.408884,5.982308,7.672395,4.612153,5.388172
106,8.512052,170.189296,0.628903,2.208000,1994.866000,3902.175000,22.595240,14.900000,6.264412,5.214563,...,5.870257,7.375095,6.141559,6.524219,6.445696,7.479272,7.450028,7.152987,4.644567,5.573207
107,9.155818,173.077638,0.591969,6.290000,1041.105000,8203.203633,20.485000,3.600000,9.701289,16.053098,...,3.700000,7.600000,7.700000,5.000000,2.900000,8.100000,6.800000,4.400000,2.000000,2.700000
108,7.785321,181.684410,0.693319,3.538864,10556.574011,18461.711101,23.462981,70.675985,8.784990,17.181995,...,5.299963,6.565667,6.000978,5.685404,5.813596,5.894994,5.563714,6.582911,4.567869,5.365322
109,7.785926,181.682765,0.687973,3.543006,10556.204373,18459.469047,23.463359,74.232615,8.243125,17.223126,...,6.400000,7.550000,5.300000,6.800000,5.700000,6.150000,6.200000,6.250000,4.400000,6.400000

# LET'S MODEL SOME SHT

In [230]:
imputed_final_df['target'] = 1
imputed_control['target']=0

In [233]:
full_dataset = pd.concat([imputed_control,imputed_final_df])

full_dataset

,Military spending percent of total government spending,Arms imports million constant U.S. dollars,Human Development Index (0 - 1),Economic growth: the rate of change of real GDP,GDP per capita current U.S. dollars,GDP per capita Purchasing Power Parity,Capital investment as percent of GDP,Inflation: percent change in the Consumer Price Index,Unemployment rate,Youth unemployment ages 15-24,...,Factionalized elites index 0 (low) - 10 (high),Group grievance index 0 (low) - 10 (high),Economic decline index 0 (low) - 10 (high),Uneven economic development index 0 (low) - 10 (high),State legitimacy index 0 (high) - 10 (low),Human rights and rule of law index 0 (high) - 10 (low),Demographic pressures 0 (low) - 10 (high),Refugees and displaced persons index 0 (low) - 10 (high),External interventions index 0 (low) - 10 (high),target
0,4.292091,209.322106,0.790600,-2.625,40601.665,51634.628689,35.810000,84.564378,9.634465,21.852287,...,4.552520,4.725486,3.562728,4.191069,2.974549,1.353090,5.025372,3.488201,3.154603,0
1,6.030000,69.500000,0.853000,1.680,8598.414,4032.150000,22.532515,2284.975000,4.150000,8.892500,...,11.042710,6.053335,6.854513,6.672058,-10.885526,1.448891,19.597985,4.853890,5.455294,0
2,8.609929,363.800000,0.647129,2.118,2154.510,9188.155848,28.954000,108.821431,8.782994,19.040874,...,7.884200,6.126349,6.188445,6.106055,7.659240,6.542294,8.028683,4.600025,5.923024,0
3,5.760000,93.000000,0.723600,5.654,6883.974,16839.540000,17.900000,166.338771,10.492000,22.108000,...,7.562185,6.034932,5.873138,5.889429,5.930206,5.612593,8.378061,4.560561,5.797720,0
4,12.438000,3.000000,0.626400,7.120,541.122,3429.844000,28.754000,3.200000,9.976000,19.042000,...,7.478919,6.275339,6.635955,6.568458,9.459550,8.990200,7.660674,4.736830,5.697834,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,5.447500,44.500000,0.762750,2.226,6700.366,12416.858000,20.810000,2.620000,4.514000,9.702000,...,7.100000,8.000000,3.680000,6.840000,7.000000,3.780000,6.200000,4.060000,2.900000,1
107,6.227500,12.750000,0.758000,0.024,6058.920,11097.980000,24.668000,0.060000,4.744000,10.090000,...,8.200000,6.700000,5.880000,6.380000,6.020000,4.360000,6.100000,5.620000,5.700000,1
108,9.122637,76.666667,0.711750,4.954,1806.112,7270.168000,37.868000,-97.933434,6.338000,14.324000,...,8.800000,6.580000,5.820000,6.280000,9.440000,8.200000,5.140000,4.980000,4.220000,1
109,10.237500,68.000000,0.779500,1.844,3898.644,12784.654000,28.120000,5.300000,4.798000,22.266000,...,8.980000,8.880000,5.440000,6.500000,6.660000,8.280000,6.060000,7.800000,6.060000,1
110,4.477500,276.000000,0.818000,2.840,9607.188,25630.774000,26.940000,6.325000,4.868000,3.800000,...,7.600000,7.960000,5.740000,3.640000,8.380000,6.820000,4.060000,2.500000,3.600000,1

In [301]:
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV

X = full_dataset.drop(columns='target')
y = full_dataset['target']
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size = 0.3)

In [302]:
bst = XGBClassifier(n_estimators=2, max_depth=2, learning_rate=1, objective='binary:logistic')

In [303]:
bst.fit(X_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, feature_types=None, gamma=0, gpu_id=-1,
              grow_policy='depthwise', importance_type=None,
              interaction_constraints='', learning_rate=1, max_bin=256,
              max_cat_threshold=64, max_cat_to_onehot=4, max_delta_step=0,
              max_depth=2, max_leaves=0, min_child_weight=1, missing=nan,
              monotone_constraints='()', n_estimators=2, n_jobs=0,
              num_parallel_tree=1, predictor='auto', random_state=0, ...)

In [304]:
bst.feature_importances_

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.09650128, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.08096263,
       0.        , 0.05125221, 0.7087168 , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.06256709, 0.        ,
       0.        , 0.        ], dtype=float32)

In [305]:
preds = bst.predict(X_test)

accuracy_score(preds,y_test)

0.8507462686567164

In [306]:
import pandas as pd

features = bst.get_booster().feature_names
importances = bst.feature_importances_
feature_importances_df = pd.DataFrame(zip(features, importances), columns=['feature', 'importance']).set_index('feature')
feature_importances_df.sort_values('importance', ascending=False).head(10)

                                                    importance
feature
Security threats index 0 (low) - 10 (high)            0.708717
Voice and accountability index (-2.5 weak; 2.5 ...    0.096501
Political globalization index (0-100)                 0.080963
Human rights and rule of law index 0 (high) - 1...    0.062567
Homicides per 100000 people                           0.051252
Military spending percent of total government s...    0.000000
Life expectancy in years                              0.000000
Population growth percent                             0.000000
Refugee population                                    0.000000
Rural population percent of total population          0.000000

# Downloading the data

In [307]:
full_dataset.to_csv('full_dataset.csv')

In [308]:
imputed_control.to_csv('imputed_control.csv')

In [309]:
imputed_final_df.to_csv('imputed_final_df.csv')